"""用户命名版本（本地工作区）—— 云端 labeled snapshot 的本机对位实现。

盘上布局（工作区旁路内部区，与软删区 ``AgentCore/trash/<id>/`` 同构）::

    <workspace_root>/AgentCore/versions/<version_id>/
        meta.json     # {"version_id", "name", "created_at", "size_bytes"}
        content.zip   # zip_dir(workspace_root)

与 ``turn_baseline`` 的分野：回合基线是 best-effort（失败只打日志、返 ``None``、
永不阻断回合），**命名版本是用户显式动作**——任何失败都抛出，由调用方如实报错，
绝不静默吞掉后让用户以为「已留版本」。

保留策略：用户命名版本**永不自动清理**（对齐云端既有定案）；只有显式
:func:`delete_workspace_version` 会删。软删区那套 30 天保留期不适用于这里。
"""

from __future__ import annotations

import asyncio
import json
import re
import shutil
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from agentcore.storage._archive import new_snapshot_id, unzip_into, zip_dir
from agentcore.workspace.stage_dirs import VERSIONS_REL

META_NAME = "meta.json"
CONTENT_NAME = "content.zip"

# Same ceiling as the local turn baseline / desktop handoff (ARCHIVE_MAX_*): a
# named version zips the same tree. Unlike the baseline these raise instead of
# degrading to "no version".
VERSION_MAX_FILES = 20_000
VERSION_MAX_BYTES = 100 * 1024 * 1024  # 100 MiB raw

#: Longest accepted user label. Names never touch the filesystem (the generated
#: ``version_id`` is the directory name), so this is a UI/storage sanity bound.
VERSION_NAME_MAX_LEN = 200

# Ids are generated by ``new_snapshot_id`` (``YYYYMMDDTHHMMSSZ-<hex8>``); the
# guard exists because ids also arrive from the renderer on restore / delete.
_VERSION_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$")


class WorkspaceVersionError(Exception):
    """Base for named-version failures (never swallowed — surfaced to the user)."""


class InvalidVersionIdError(WorkspaceVersionError):
    """The version id is malformed (path separators / traversal / bad charset)."""

    def __init__(self, version_id: str) -> None:
        self.version_id = version_id
        super().__init__(f"invalid version id: {version_id!r}")


class InvalidVersionNameError(WorkspaceVersionError):
    """The user-supplied version name is blank or over the length bound."""


class VersionNotFoundError(WorkspaceVersionError):
    """No usable version (meta + content) exists for this id."""

    def __init__(self, version_id: str) -> None:
        self.version_id = version_id
        super().__init__(f"workspace version not found: {version_id}")


@dataclass(frozen=True)
class WorkspaceVersion:
    """One named version's metadata (mirrors cloud ``SnapshotSummary`` fields)."""

    version_id: str
    name: str
    created_at: str
    size_bytes: int

    def to_wire(self) -> dict[str, object]:
        """snake_case payload for the sidecar JSON-RPC reply / ``meta.json``."""
        return {
            "version_id": self.version_id,
            "name": self.name,
            "created_at": self.created_at,
            "size_bytes": self.size_bytes,
        }


def versions_root(workspace_root: Path) -> Path:
    """``<workspace_root>/AgentCore/versions`` (not created)."""
    return workspace_root / Path(*VERSIONS_REL.split("/"))


def version_dir(workspace_root: Path, version_id: str) -> Path:
    """Directory holding one version's ``meta.json`` + ``content.zip``.

    Raises :exc:`InvalidVersionIdError` before any path join, so a caller-supplied
    id can never escape the versions zone.
    """
    if not is_valid_version_id(version_id):
        raise InvalidVersionIdError(version_id)
    return versions_root(workspace_root) / version_id


def is_valid_version_id(version_id: str) -> bool:
    """Whether ``version_id`` is a safe single path segment."""
    if not isinstance(version_id, str):
        return False
    candidate = version_id.strip()
    if candidate in ("", ".", ".."):
        return False
    if "/" in candidate or "\\" in candidate or "\0" in candidate:
        return False
    return bool(_VERSION_ID_RE.match(candidate))


def normalize_version_name(name: str) -> str:
    """Trim + validate a user label. Raises :exc:`InvalidVersionNameError`."""
    cleaned = (name or "").strip()
    if not cleaned:
        raise InvalidVersionNameError("版本名不能为空")
    if len(cleaned) > VERSION_NAME_MAX_LEN:
        raise InvalidVersionNameError(f"版本名不能超过 {VERSION_NAME_MAX_LEN} 字")
    return cleaned


def _read_version_meta(entry_dir: Path) -> WorkspaceVersion | None:
    """Parse one version dir, or ``None`` when it is missing / malformed.

    Requires ``content.zip`` to exist: a meta-only directory is a half-written
    create, and listing it would advertise a restore point that cannot restore.
    """
    if not (entry_dir / CONTENT_NAME).is_file():
        return None
    try:
        raw = json.loads((entry_dir / META_NAME).read_text(encoding="utf-8"))
    except (OSError, ValueError, UnicodeDecodeError):
        return None
    if not isinstance(raw, dict):
        return None
    name = raw.get("name")
    created_at = raw.get("created_at")
    if not isinstance(name, str) or not name.strip():
        return None
    if not isinstance(created_at, str) or not created_at.strip():
        return None
    version_id = raw.get("version_id")
    if not isinstance(version_id, str) or version_id != entry_dir.name:
        # Directory name is authoritative — a mismatched meta would make
        # restore/delete address a different version than the one listed.
        version_id = entry_dir.name
    try:
        size_bytes = int(raw.get("size_bytes", 0))
    except (TypeError, ValueError):
        size_bytes = 0
    return WorkspaceVersion(
        version_id=version_id,
        name=name,
        created_at=created_at,
        size_bytes=max(0, size_bytes),
    )


def _list_workspace_versions_sync(workspace_root: Path) -> list[WorkspaceVersion]:
    root = versions_root(workspace_root)
    try:
        children = sorted(p for p in root.iterdir() if p.is_dir())
    except FileNotFoundError:
        return []
    except OSError as e:
        raise WorkspaceVersionError(f"读取版本区失败：{e}") from e
    out: list[WorkspaceVersion] = []
    for entry_dir in children:
        if not is_valid_version_id(entry_dir.name):
            continue
        meta = _read_version_meta(entry_dir)
        if meta is not None:
            out.append(meta)
    # Newest first (ids are time-sortable; created_at is the honest key).
    out.sort(key=lambda v: (v.created_at, v.version_id), reverse=True)
    return out


def _create_workspace_version_sync(workspace_root: Path, name: str) -> WorkspaceVersion:
    label = normalize_version_name(name)
    if not workspace_root.is_dir():
        raise WorkspaceVersionError(f"工作区目录不存在：{workspace_root}")
    version_id = new_snapshot_id()
    entry_dir = versions_root(workspace_root) / version_id
    # ``zip_dir`` prunes the path-aware internal zones, so a version never
    # contains earlier versions / baselines / the code index.
    data = zip_dir(
        workspace_root,
        max_files=VERSION_MAX_FILES,
        max_bytes=VERSION_MAX_BYTES,
    )
    created_at = datetime.now(UTC).isoformat()
    version = WorkspaceVersion(
        version_id=version_id,
        name=label,
        created_at=created_at,
        size_bytes=len(data),
    )
    try:
        entry_dir.mkdir(parents=True, exist_ok=True)
        content = entry_dir / CONTENT_NAME
        tmp = content.with_suffix(".zip.tmp")
        tmp.write_bytes(data)
        tmp.replace(content)
        # meta last: listing requires both, so a crash mid-create stays invisible
        # rather than advertising a restore point.
        (entry_dir / META_NAME).write_text(
            json.dumps(version.to_wire(), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
    except OSError as e:
        shutil.rmtree(entry_dir, ignore_errors=True)
        raise WorkspaceVersionError(f"写入版本失败：{e}") from e
    return version


def _restore_workspace_version_sync(workspace_root: Path, version_id: str) -> WorkspaceVersion:
    entry_dir = version_dir(workspace_root, version_id.strip())
    meta = _read_version_meta(entry_dir)
    if meta is None:
        raise VersionNotFoundError(version_id)
    try:
        data = (entry_dir / CONTENT_NAME).read_bytes()
    except OSError as e:
        raise WorkspaceVersionError(f"读取版本内容失败：{e}") from e
    # Overlay, not mirror — same semantics as the local turn-baseline restore:
    # files created after the version are left alone.
    unzip_into(data, workspace_root)
    return meta


def _delete_workspace_version_sync(workspace_root: Path, version_id: str) -> None:
    entry_dir = version_dir(workspace_root, version_id.strip())
    if not entry_dir.is_dir():
        raise VersionNotFoundError(version_id)
    try:
        shutil.rmtree(entry_dir)
    except OSError as e:
        raise WorkspaceVersionError(f"删除版本失败：{e}") from e


async def list_workspace_versions(*, workspace_root: Path) -> list[WorkspaceVersion]:
    """Named versions for this workspace, newest first (missing zone → empty)."""
    return await asyncio.to_thread(_list_workspace_versions_sync, workspace_root)


async def create_workspace_version(*, workspace_root: Path, name: str) -> WorkspaceVersion:
    """Zip the workspace into a new named version. Raises on any failure.

    Raises :exc:`InvalidVersionNameError`, :exc:`WorkspaceVersionError`, or
    ``ArchiveLimitError`` when the tree exceeds :data:`VERSION_MAX_FILES` /
    :data:`VERSION_MAX_BYTES`.
    """
    return await asyncio.to_thread(_create_workspace_version_sync, workspace_root, name)


async def restore_workspace_version(
    *, workspace_root: Path, version_id: str
) -> WorkspaceVersion:
    """Overlay a named version's zip onto the workspace (never cloud restore)."""
    return await asyncio.to_thread(
        _restore_workspace_version_sync, workspace_root, version_id
    )


async def delete_workspace_version(*, workspace_root: Path, version_id: str) -> None:
    """Remove one named version directory. Raises when it does not exist."""
    await asyncio.to_thread(_delete_workspace_version_sync, workspace_root, version_id)


__all__ = [
    "CONTENT_NAME",
    "META_NAME",
    "VERSION_MAX_BYTES",
    "VERSION_MAX_FILES",
    "VERSION_NAME_MAX_LEN",
    "InvalidVersionIdError",
    "InvalidVersionNameError",
    "VersionNotFoundError",
    "WorkspaceVersion",
    "WorkspaceVersionError",
    "create_workspace_version",
    "delete_workspace_version",
    "is_valid_version_id",
    "list_workspace_versions",
    "normalize_version_name",
    "restore_workspace_version",
    "version_dir",
    "versions_root",
]
