/*
 * AUTO-GENERATED by scripts/precompute-layout.mts — do not edit by hand.
 * Re-run `pnpm layout` after changing the sample DAG in src/kit/hero/demo.ts.
 *
 * Baked ELK coordinates (layout="leftright"), so promo stills render with
 * zero async layout at frame time.
 */

export interface DemoLayout {
  positions: Record<string, { x: number; y: number }>;
  width: number;
  height: number;
}

export const DEMO_LAYOUT: DemoLayout = {
  "positions": {
    "__input__": {
      "x": 24,
      "y": 273
    },
    "research_user": {
      "x": 314,
      "y": 107
    },
    "research_comp": {
      "x": 314,
      "y": 273
    },
    "research_tech": {
      "x": 314,
      "y": 439
    },
    "moderator": {
      "x": 604,
      "y": 273
    },
    "view_growth": {
      "x": 894,
      "y": 24
    },
    "view_steady": {
      "x": 894,
      "y": 190
    },
    "view_user": {
      "x": 894,
      "y": 356
    },
    "view_cost": {
      "x": 894,
      "y": 522
    },
    "strategy": {
      "x": 1184,
      "y": 273
    },
    "spec_product": {
      "x": 1474,
      "y": 190
    },
    "spec_tech": {
      "x": 1474,
      "y": 356
    },
    "captain": {
      "x": 1764,
      "y": 273
    }
  },
  "width": 1998,
  "height": 656
};
