/*
 * AUTO-GENERATED by scripts/precompute-layout.mts — do not edit by hand.
 * Re-run `pnpm layout` after changing the sample DAG in src/kit/hero/demo.ts.
 *
 * Baked ELK coordinates (layout="leftright"), so stills render with
 * zero async layout at frame time.
 */

export interface DemoLayout {
  positions: Record<string, { x: number; y: number }>;
  width: number;
  height: number;
}

export const DEMO_LAYOUT: DemoLayout = {
  "positions": {
    "__input__": {
      "x": 24,
      "y": 190
    },
    "pricing": {
      "x": 314,
      "y": 24
    },
    "pain": {
      "x": 314,
      "y": 190
    },
    "channel": {
      "x": 314,
      "y": 356
    },
    "captain": {
      "x": 604,
      "y": 190
    }
  },
  "width": 838,
  "height": 490
};
