"""Pydantic request/response schemas for the API layer, split by domain.

This package was split out of a single ``schemas.py`` along domain seams
(file-splitting.mdc). This ``__init__`` re-exports the full public surface so the
historical import path — ``from agentcore.api.schemas import X`` — keeps working
unchanged across the codebase, and the OpenAPI spec (single source for the TS
types, see scripts/dump_openapi.py) is byte-identical to the pre-split build.
"""

from .admin import (
    AdminAuditLogLine,
    AdminAuditLogListResponse,
    AdminConversationLine,
    AdminConversationListItem,
    AdminConversationListResponse,
    AdminConversationReplay,
    AdminObservabilitySummary,
    AdminOverview,
    AdminResetPasswordResponse,
    AdminSetPasswordRequest,
    AdminSystemStatus,
    AdminTurnListItem,
    AdminTurnListResponse,
    AdminUpdateUserRequest,
    AdminUsageSummary,
    AdminUserCostLine,
    AdminUserDetail,
    AdminUserListItem,
    AdminUserListResponse,
    AdminUserResponse,
    DailyTurns,
    ReplayConversation,
    ReplayMessage,
    ReplaySpan,
    TurnHealthWindow,
    TurnMetricLine,
)
from .auth import (
    BatchCreateInviteRequest,
    ChangePasswordRequest,
    CreateInviteRequest,
    DeleteAccountRequest,
    InviteListResponse,
    InviteResponse,
    InviteStatsResponse,
    LoginMfaRequest,
    LoginRequest,
    LoginResponse,
    MfaConfirmRequest,
    MfaConfirmResponse,
    MfaSetupResponse,
    MfaStatusResponse,
    RegisterRequest,
    SessionListResponse,
    SessionSummary,
    TokenRefreshRequest,
    TokenResponse,
    TokenRevokeRequest,
    UpdateProfileRequest,
    UserResponse,
)
from .boards import (
    BoardConversationResponse,
    BoardDetail,
    BoardSceneWriteRequest,
    BoardSummary,
    BoardWriteResult,
    CreateBoardRequest,
    UpdateBoardRequest,
)
from .bookmarks import (
    BookmarkIdsResponse,
    BookmarkItem,
    BookmarkListResponse,
    CreateBookmarkRequest,
)
from .common import StatusResponse
from .conversations import (
    ConversationListResponse,
    ConversationSummary,
    CreateConversationRequest,
    CreateFolderRequest,
    FolderGroup,
    FolderSummary,
    GroupedConversationsResponse,
    PermissionPresetUpdate,
    UpdateConversationRequest,
    UpdateFolderRequest,
)
from .demo_tape import (
    DemoTapeCatalogResponse,
    DemoTapePrepareRequest,
    DemoTapePrepareResponse,
    DemoTapeStartRequest,
    DemoTapeStartResponse,
    DemoTapeSummary,
)
from .devices import DeviceListResponse, DeviceRegistration, DeviceSummary
from .feedback import (
    AdminFeedbackSummary,
    CreateFeedbackRequest,
    FeedbackListResponse,
    FeedbackSummary,
    UpdateFeedbackStatusRequest,
)
from .files import RewriteRequest, RewriteResponse
from .handoff import (
    ApplyHandoffRequest,
    DispatchHandoffRequest,
    HandoffApplySelection,
    HandoffDiffResponse,
    HandoffFileChange,
    HandoffJobListResponse,
    HandoffJobSummary,
)
from .llm_key import LlmKeyStatusResponse, SetBillingPreferenceRequest, SetLlmKeyRequest
from .messages import (
    AcceptRunOutcomeRequest,
    AcceptRunOutcomeResponse,
    Citation,
    MemoryUpdateItemView,
    MemoryUpdateView,
    MessageAttachment,
    MessageDetail,
    MessageListResponse,
    PausedTurnSummary,
    PendingApprovalSummary,
    PendingInteractionSummary,
    RecordTurnRequest,
    RecordTurnResponse,
    RegenerateMessageRequest,
    ResolveApprovalInteraction,
    ResolveClientToolInteraction,
    ResolveDelegationAuthorizationInteraction,
    ResolveEscalationInteraction,
    ResolveInteractionRequest,
    ResumeTurnRequest,
    RetryFailedRequest,
    RunsPayload,
    SendMessageRequest,
    SetMessageFeedbackRequest,
    StopTurnResponse,
    StoredAttachment,
    SubmitDebateSteerRequest,
    SubmitDebateSteerResponse,
    SubmitRunRedirectRequest,
    SubmitRunRedirectResponse,
    TurnRecoveryResponse,
    WorkspaceOpError,
    interaction_result_from_body,
)
from .messaging import (
    AdminMuteRequest,
    AnnounceRequest,
    BlockedUser,
    BlockListResponse,
    BlockUserRequest,
    ChatFileUploadResponse,
    ChatListResponse,
    ChatMembersResponse,
    ChatMessageDetail,
    ChatMessageListResponse,
    ChatParticipant,
    ChatSummary,
    DirectorySettings,
    MarkReadRequest,
    SendChatMessageRequest,
    StartDmRequest,
    UpdateDirectorySettingsRequest,
    UpdateMembershipRequest,
    UserSearchResponse,
    UserSearchResult,
)
from .search import SearchItem, SearchResponse, SearchSection
from .sharing import CreateShareRequest, ShareListResponse, ShareSummary
from .tools import (
    CapabilitiesResponse,
    CapabilityGuidelines,
    CapabilitySkill,
    CapabilityTool,
)
from .usage import (
    AgentCostLine,
    ConversationCost,
    CostBreakdown,
    DailyCost,
    QuotaStatus,
    RoleCostLine,
    TurnCost,
    UsageBreakdown,
    UsageSummary,
    UsageWindow,
)
from .workspaces import (
    BindLocalWorkspaceRequest,
    CloneRepoRequest,
    CloneRepoResponse,
    CreateDirRequest,
    CreateSnapshotRequest,
    ExternalGrantItem,
    ExternalGrantListResponse,
    ExternalGrantResponse,
    GrantExternalReadonlyRequest,
    MoveFileRequest,
    SnapshotListResponse,
    SnapshotSummary,
    UploadFileResponse,
    WorkspaceBindingResponse,
    WorkspaceEditDoc,
    WorkspaceFileEntry,
    WorkspaceFileIndexResponse,
    WorkspaceFileListResponse,
    WorkspaceListResponse,
    WorkspaceSummary,
    WorkspaceWriteRequest,
    WorkspaceWriteResult,
)

__all__ = [
    # auth
    "RegisterRequest",
    "LoginRequest",
    "LoginMfaRequest",
    "LoginResponse",
    "MfaConfirmRequest",
    "MfaConfirmResponse",
    "MfaSetupResponse",
    "MfaStatusResponse",
    "ChangePasswordRequest",
    "UpdateProfileRequest",
    "DeleteAccountRequest",
    "UserResponse",
    "TokenResponse",
    "SessionSummary",
    "SessionListResponse",
    "TokenRefreshRequest",
    "TokenRevokeRequest",
    "CreateInviteRequest",
    "BatchCreateInviteRequest",
    "InviteResponse",
    "InviteListResponse",
    "InviteStatsResponse",
    # admin
    "AdminUserResponse",
    "AdminUserListItem",
    "AdminUserListResponse",
    "AdminUpdateUserRequest",
    "AdminResetPasswordResponse",
    "AdminSetPasswordRequest",
    "AdminUserCostLine",
    "AdminUsageSummary",
    "AdminSystemStatus",
    "TurnHealthWindow",
    "DailyTurns",
    "TurnMetricLine",
    "AdminObservabilitySummary",
    "AdminOverview",
    "AdminAuditLogLine",
    "AdminAuditLogListResponse",
    "AdminConversationLine",
    "AdminConversationListItem",
    "AdminConversationListResponse",
    "AdminTurnListItem",
    "AdminTurnListResponse",
    "AdminUserDetail",
    "ReplaySpan",
    "ReplayMessage",
    "ReplayConversation",
    "AdminConversationReplay",
    # conversations + folders
    "CreateConversationRequest",
    "ConversationSummary",
    "ConversationListResponse",
    "UpdateConversationRequest",
    "PermissionPresetUpdate",
    "CreateFolderRequest",
    "UpdateFolderRequest",
    "FolderSummary",
    "FolderGroup",
    "GroupedConversationsResponse",
    # boards (AI 协作白板)
    "CreateBoardRequest",
    "UpdateBoardRequest",
    "BoardSummary",
    "BoardDetail",
    "BoardSceneWriteRequest",
    "BoardWriteResult",
    "BoardConversationResponse",
    # bookmarks (消息收藏)
    "CreateBookmarkRequest",
    "BookmarkItem",
    "BookmarkListResponse",
    "BookmarkIdsResponse",
    # llm key
    "SetLlmKeyRequest",
    "SetBillingPreferenceRequest",
    "LlmKeyStatusResponse",
    # workspaces
    "BindLocalWorkspaceRequest",
    "WorkspaceBindingResponse",
    "ExternalGrantItem",
    "ExternalGrantListResponse",
    "ExternalGrantResponse",
    "GrantExternalReadonlyRequest",
    "WorkspaceSummary",
    "WorkspaceListResponse",
    "CreateSnapshotRequest",
    "SnapshotSummary",
    "SnapshotListResponse",
    "WorkspaceFileEntry",
    "WorkspaceFileListResponse",
    "WorkspaceFileIndexResponse",
    "UploadFileResponse",
    "WorkspaceEditDoc",
    "WorkspaceWriteRequest",
    "WorkspaceWriteResult",
    "MoveFileRequest",
    "CreateDirRequest",
    "CloneRepoRequest",
    "CloneRepoResponse",
    # messages + interactions + turns
    "MessageAttachment",
    "StoredAttachment",
    "SendMessageRequest",
    "RegenerateMessageRequest",
    "RetryFailedRequest",
    "SetMessageFeedbackRequest",
    "ResolveApprovalInteraction",
    "WorkspaceOpError",
    "ResolveClientToolInteraction",
    "ResolveEscalationInteraction",
    "ResolveDelegationAuthorizationInteraction",
    "ResolveInteractionRequest",
    "interaction_result_from_body",
    "ResumeTurnRequest",
    "SubmitDebateSteerRequest",
    "SubmitDebateSteerResponse",
    "SubmitRunRedirectRequest",
    "SubmitRunRedirectResponse",
    "AcceptRunOutcomeRequest",
    "AcceptRunOutcomeResponse",
    "PausedTurnSummary",
    "PendingApprovalSummary",
    "PendingInteractionSummary",
    "TurnRecoveryResponse",
    "Citation",
    "RunsPayload",
    "MemoryUpdateItemView",
    "MemoryUpdateView",
    "MessageDetail",
    "MessageListResponse",
    "RecordTurnRequest",
    "RecordTurnResponse",
    "StopTurnResponse",
    # search
    "SearchItem",
    "SearchSection",
    "SearchResponse",
    # sharing
    "ShareSummary",
    "CreateShareRequest",
    "ShareListResponse",
    # devices
    "DeviceRegistration",
    "DeviceSummary",
    "DeviceListResponse",
    # feedback
    "CreateFeedbackRequest",
    "FeedbackSummary",
    "FeedbackListResponse",
    "UpdateFeedbackStatusRequest",
    "AdminFeedbackSummary",
    # handoff
    "DispatchHandoffRequest",
    "HandoffJobSummary",
    "HandoffJobListResponse",
    "HandoffFileChange",
    "HandoffDiffResponse",
    "HandoffApplySelection",
    "ApplyHandoffRequest",
    # tools + capabilities
    "CapabilityTool",
    "CapabilitySkill",
    "CapabilityGuidelines",
    "CapabilitiesResponse",
    # cost & usage
    "CostBreakdown",
    "UsageBreakdown",
    "AgentCostLine",
    "TurnCost",
    "ConversationCost",
    "UsageWindow",
    "QuotaStatus",
    "RoleCostLine",
    "DailyCost",
    "UsageSummary",
    # messaging (IM)
    "UserSearchResult",
    "UserSearchResponse",
    "ChatParticipant",
    "ChatSummary",
    "ChatListResponse",
    "ChatMembersResponse",
    "StartDmRequest",
    "UpdateMembershipRequest",
    "AdminMuteRequest",
    "AnnounceRequest",
    "ChatMessageDetail",
    "ChatMessageListResponse",
    "SendChatMessageRequest",
    "ChatFileUploadResponse",
    "MarkReadRequest",
    "DirectorySettings",
    "UpdateDirectorySettingsRequest",
    "BlockUserRequest",
    "BlockedUser",
    "BlockListResponse",
    # file assist
    "RewriteRequest",
    "RewriteResponse",
    # demo-tape (dev-only)
    "DemoTapeSummary",
    "DemoTapeCatalogResponse",
    "DemoTapePrepareRequest",
    "DemoTapePrepareResponse",
    "DemoTapeStartRequest",
    "DemoTapeStartResponse",
    # generic
    "StatusResponse",
]
