"""Pydantic request/response schemas for the API layer, split by domain.

This package was split out of a single ``schemas.py`` along domain seams
(file-splitting.mdc). This ``__init__`` re-exports the full public surface so the
historical import path — ``from agentcore.api.schemas import X`` — keeps working
unchanged across the codebase, and the OpenAPI spec (single source for the TS
types, see scripts/dump_openapi.py) is byte-identical to the pre-split build.
"""

from .admin import (
    AdminAuditLogLine,
    AdminAuditLogListResponse,
    AdminConversationLine,
    AdminConversationListItem,
    AdminConversationListResponse,
    AdminConversationReplay,
    AdminObservabilitySummary,
    AdminOverview,
    AdminResetPasswordResponse,
    AdminSetPasswordRequest,
    AdminSystemStatus,
    AdminTurnListItem,
    AdminTurnListResponse,
    AdminUpdateUserRequest,
    AdminUsageSummary,
    AdminUserCostLine,
    AdminUserDetail,
    AdminUserListItem,
    AdminUserListResponse,
    AdminUserResponse,
    DailyTurns,
    ReplayConversation,
    ReplayMessage,
    ReplaySpan,
    TurnHealthWindow,
    TurnMetricLine,
)
from .auth import (
    BatchCreateInviteRequest,
    ChangePasswordRequest,
    CreateInviteRequest,
    DeleteAccountRequest,
    InviteListResponse,
    InviteResponse,
    LoginRequest,
    RegisterRequest,
    TokenRefreshRequest,
    TokenResponse,
    TokenRevokeRequest,
    UpdateProfileRequest,
    UserResponse,
)
from .common import StatusResponse
from .conversations import (
    ConversationListResponse,
    ConversationSummary,
    CreateConversationRequest,
    CreateFolderRequest,
    FolderGroup,
    FolderSummary,
    GroupedConversationsResponse,
    MoveConversationRequest,
    UpdateConversationRequest,
    UpdateFolderRequest,
)
from .devices import DeviceListResponse, DeviceRegistration, DeviceSummary
from .files import RewriteRequest, RewriteResponse
from .handoff import (
    ApplyHandoffRequest,
    DispatchHandoffRequest,
    HandoffApplySelection,
    HandoffDiffResponse,
    HandoffFileChange,
    HandoffJobListResponse,
    HandoffJobSummary,
)
from .llm_key import LlmKeyStatusResponse, SetLlmKeyRequest
from .messages import (
    Citation,
    MessageAttachment,
    MessageDetail,
    MessageListResponse,
    PausedTurnListResponse,
    PausedTurnSummary,
    RecordTurnRequest,
    RecordTurnResponse,
    RegenerateMessageRequest,
    ResolveApprovalInteraction,
    ResolveCheckpointInteraction,
    ResolveClientToolInteraction,
    ResolveDebateRoundInteraction,
    ResolveEscalationInteraction,
    ResolveInteractionRequest,
    ResolvePlanReviewInteraction,
    ResumeTurnRequest,
    RunsPayload,
    SendMessageRequest,
    StopTurnResponse,
    StoredAttachment,
    WorkspaceOpError,
    interaction_result_from_body,
)
from .messaging import (
    AdminMuteRequest,
    AnnounceRequest,
    BlockedUser,
    BlockListResponse,
    BlockUserRequest,
    ChatFileUploadResponse,
    ChatListResponse,
    ChatMembersResponse,
    ChatMessageDetail,
    ChatMessageListResponse,
    ChatParticipant,
    ChatSummary,
    DirectorySettings,
    MarkReadRequest,
    SendChatMessageRequest,
    StartDmRequest,
    UpdateDirectorySettingsRequest,
    UpdateMembershipRequest,
    UserSearchResponse,
    UserSearchResult,
)
from .model_modes import (
    CreateModelModeRequest,
    ModelModeCatalog,
    ModelModePreset,
    ModelModesResponse,
    ModelModeSummary,
    ModelRoleOption,
    SetDefaultModeRequest,
    UpdateModelModeRequest,
)
from .search import SearchItem, SearchResponse, SearchSection
from .sharing import CreateShareRequest, ShareListResponse, ShareSummary
from .tools import (
    CapabilitiesResponse,
    CapabilityGuidelines,
    CapabilitySkill,
    CapabilityTool,
    ToolInfo,
    ToolListResponse,
)
from .usage import (
    AgentCostLine,
    ConversationCost,
    CostBreakdown,
    DailyCost,
    QuotaStatus,
    RoleCostLine,
    TurnCost,
    UsageBreakdown,
    UsageSummary,
    UsageWindow,
)
from .workspaces import (
    BindLocalWorkspaceRequest,
    CloneRepoRequest,
    CloneRepoResponse,
    CreateDirRequest,
    CreateSnapshotRequest,
    MoveFileRequest,
    SnapshotListResponse,
    SnapshotSummary,
    UploadFileResponse,
    WorkspaceBindingResponse,
    WorkspaceEditDoc,
    WorkspaceFileEntry,
    WorkspaceFileIndexResponse,
    WorkspaceFileListResponse,
    WorkspaceListResponse,
    WorkspaceSummary,
    WorkspaceWriteRequest,
    WorkspaceWriteResult,
)

__all__ = [
    # auth
    "RegisterRequest",
    "LoginRequest",
    "ChangePasswordRequest",
    "UpdateProfileRequest",
    "DeleteAccountRequest",
    "UserResponse",
    "TokenResponse",
    "TokenRefreshRequest",
    "TokenRevokeRequest",
    "CreateInviteRequest",
    "BatchCreateInviteRequest",
    "InviteResponse",
    "InviteListResponse",
    # admin
    "AdminUserResponse",
    "AdminUserListItem",
    "AdminUserListResponse",
    "AdminUpdateUserRequest",
    "AdminResetPasswordResponse",
    "AdminSetPasswordRequest",
    "AdminUserCostLine",
    "AdminUsageSummary",
    "AdminSystemStatus",
    "TurnHealthWindow",
    "DailyTurns",
    "TurnMetricLine",
    "AdminObservabilitySummary",
    "AdminOverview",
    "AdminAuditLogLine",
    "AdminAuditLogListResponse",
    "AdminConversationLine",
    "AdminConversationListItem",
    "AdminConversationListResponse",
    "AdminTurnListItem",
    "AdminTurnListResponse",
    "AdminUserDetail",
    "ReplaySpan",
    "ReplayMessage",
    "ReplayConversation",
    "AdminConversationReplay",
    # conversations + folders
    "CreateConversationRequest",
    "ConversationSummary",
    "ConversationListResponse",
    "UpdateConversationRequest",
    "MoveConversationRequest",
    "CreateFolderRequest",
    "UpdateFolderRequest",
    "FolderSummary",
    "FolderGroup",
    "GroupedConversationsResponse",
    # model modes
    "ModelModeSummary",
    "CreateModelModeRequest",
    "UpdateModelModeRequest",
    "ModelModePreset",
    "ModelModesResponse",
    "ModelRoleOption",
    "ModelModeCatalog",
    "SetDefaultModeRequest",
    # llm key
    "SetLlmKeyRequest",
    "LlmKeyStatusResponse",
    # workspaces
    "BindLocalWorkspaceRequest",
    "WorkspaceBindingResponse",
    "WorkspaceSummary",
    "WorkspaceListResponse",
    "CreateSnapshotRequest",
    "SnapshotSummary",
    "SnapshotListResponse",
    "WorkspaceFileEntry",
    "WorkspaceFileListResponse",
    "WorkspaceFileIndexResponse",
    "UploadFileResponse",
    "WorkspaceEditDoc",
    "WorkspaceWriteRequest",
    "WorkspaceWriteResult",
    "MoveFileRequest",
    "CreateDirRequest",
    "CloneRepoRequest",
    "CloneRepoResponse",
    # messages + interactions + turns
    "MessageAttachment",
    "StoredAttachment",
    "SendMessageRequest",
    "RegenerateMessageRequest",
    "ResolveApprovalInteraction",
    "ResolveCheckpointInteraction",
    "WorkspaceOpError",
    "ResolveClientToolInteraction",
    "ResolvePlanReviewInteraction",
    "ResolveEscalationInteraction",
    "ResolveDebateRoundInteraction",
    "ResolveInteractionRequest",
    "interaction_result_from_body",
    "ResumeTurnRequest",
    "PausedTurnSummary",
    "PausedTurnListResponse",
    "Citation",
    "RunsPayload",
    "MessageDetail",
    "MessageListResponse",
    "RecordTurnRequest",
    "RecordTurnResponse",
    "StopTurnResponse",
    # search
    "SearchItem",
    "SearchSection",
    "SearchResponse",
    # sharing
    "ShareSummary",
    "CreateShareRequest",
    "ShareListResponse",
    # devices
    "DeviceRegistration",
    "DeviceSummary",
    "DeviceListResponse",
    # handoff
    "DispatchHandoffRequest",
    "HandoffJobSummary",
    "HandoffJobListResponse",
    "HandoffFileChange",
    "HandoffDiffResponse",
    "HandoffApplySelection",
    "ApplyHandoffRequest",
    # tools + capabilities
    "ToolInfo",
    "ToolListResponse",
    "CapabilityTool",
    "CapabilitySkill",
    "CapabilityGuidelines",
    "CapabilitiesResponse",
    # cost & usage
    "CostBreakdown",
    "UsageBreakdown",
    "AgentCostLine",
    "TurnCost",
    "ConversationCost",
    "UsageWindow",
    "QuotaStatus",
    "RoleCostLine",
    "DailyCost",
    "UsageSummary",
    # messaging (IM)
    "UserSearchResult",
    "UserSearchResponse",
    "ChatParticipant",
    "ChatSummary",
    "ChatListResponse",
    "ChatMembersResponse",
    "StartDmRequest",
    "UpdateMembershipRequest",
    "AdminMuteRequest",
    "AnnounceRequest",
    "ChatMessageDetail",
    "ChatMessageListResponse",
    "SendChatMessageRequest",
    "ChatFileUploadResponse",
    "MarkReadRequest",
    "DirectorySettings",
    "UpdateDirectorySettingsRequest",
    "BlockUserRequest",
    "BlockedUser",
    "BlockListResponse",
    # file assist
    "RewriteRequest",
    "RewriteResponse",
    # generic
    "StatusResponse",
]
