// AUTO-GENERATED by apps/server/scripts/dump_error_codes.py — do not edit.
// Single source: agentcore.core.error_codes.ErrorCode
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_error_codes.py)

/** The canonical code list — runtime catalog derived from backend ErrorCode. */
export const ERROR_CODES = [
  "INTERNAL_ERROR",
  "PIPELINE_ERROR",
  "STREAM_ERROR",
  "INVALID",
  "VALIDATION_ERROR",
  "NOT_FOUND",
  "CONFLICT",
  "AUTH_ERROR",
  "FORBIDDEN",
  "ADMIN_PRODUCT_FORBIDDEN",
  "MFA_REQUIRED",
  "MFA_SETUP_REQUIRED",
  "RATE_LIMITED",
  "QUOTA_EXCEEDED",
  "FREE_TIER_EXHAUSTED",
  "LLM_ERROR",
  "LLM_RATE_LIMIT",
  "LLM_TIMEOUT",
  "LLM_INSUFFICIENT_BALANCE",
  "LLM_KEY_INVALID",
  "LLM_KEY_REQUIRED",
  "PLATFORM_BILLING_UNAVAILABLE",
  "KEY_STORAGE_UNAVAILABLE",
  "TOOL_ERROR",
  "TOOL_NOT_FOUND",
  "SANDBOX_ERROR",
  "SANDBOX_TIMEOUT",
  "HANDOFF_DISPATCH_FAILED",
  "HANDOFF_FAILED",
  "HANDOFF_SNAPSHOT_NOT_FOUND",
  "HANDOFF_APPLY_FAILED",
] as const;

/** A backend error code: SSE `error` event or REST `{error:{code}}`. */
export type ErrorCode = (typeof ERROR_CODES)[number];
