// AUTO-GENERATED by apps/server/scripts/dump_sse_payload_types.py — do not edit.
// Single source: agentcore.runtime.events.payloads (pydantic wire models; factories in
// runtime/events/*.py remain the only construction path).
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_sse_payload_types.py)

import type { SSEEventType } from "./eventTypes.generated";

export type { SSEEventType } from "./eventTypes.generated";

export interface SSEEvent<T = unknown> {
  type: SSEEventType;
  timestamp: string;
  payload: T;
}

export interface MessageStartPayload {
  message_id: string;
  conversation_id: string;
  /** The turn's log correlation id (32-hex), for one-step log lookup. Omitted when the turn ran without a trace context (e.g. conformance vectors built outside a turn). */
  trace_id?: string;
}

export interface ContentDeltaPayload {
  delta: string;
}

/** 交付前核验回炉（finish_guard）：引擎丢弃自报 done 的违规正文、回炉重写。Payload-less
 * 信号——客户端清空当前流式气泡已累积的正文，再接收重写版 `content_delta`。Transport-only。 */
export type ContentResetPayload = Record<string, never>;

export interface ReasoningDeltaPayload {
  delta: string;
}

/** The CEO captain is composing a tool call's ARGUMENTS (bubble-scoped twin of
 * `RunToolProgressPayload`). Transport-only liveliness: never journaled. */
export interface ToolProgressPayload {
  tool_name: string;
  chars: number;
}

/** A running tool's coarse EXECUTION phase (工具执行阶段进度). Known values:
 * web_search → queued / querying / fallback; read_url → fetching / reading /
 * blocked; code_execute → executing. Kept as a widened `string` on the wire so
 * the backend can add phases without a client bump — an unknown value maps to a
 * generic「处理中」. */
export type ToolPhase =
  | "queued"
  | "querying"
  | "fallback"
  | "fetching"
  | "reading"
  | "executing"
  | "blocked";

/** A running tool reported an EXECUTION phase — emitted between `tool_use_start` and
 * `tool_use_end` so the waiting UI shows a live, honest state instead of a bare spinner.
 * Transport-only: NEVER journaled and NEVER folded into the process timeline. May carry
 * extra tool-specific keys (e.g. code_execute output streaming `stream`/`chunk`). */
export interface ToolUseProgressPayload {
  tool_call_id: string;
  tool_name: string;
  phase: string;
  /** Present for a delegated worker's call. */
  run_id?: string;
}

export interface ToolUseStartPayload {
  tool_call_id: string;
  tool_name: string;
  arguments: Record<string, unknown>;
  /** Present (run id) when a DELEGATED WORKER raised this call — process folds skip a tagged call (it belongs to that worker's run node, not the CEO's timeline). Absent for the captain's own calls. */
  run_id?: string;
}

/** A tool's OPTIONAL render-oriented payload (工具结果富渲染), distinct from the
 * model-facing `result` text. Opaque on the wire (snake_case). */
export type ToolDisplay = Record<string, unknown>;

export interface ToolUseEndPayload {
  tool_call_id: string;
  tool_name: string;
  result: string;
  status: "success" | "error";
  /** A tool's OPTIONAL render-oriented payload (工具结果富渲染), distinct from the model-facing `result` text. */
  display?: ToolDisplay | null;
  /** Worker-call tag; absent for the captain's own calls. */
  run_id?: string;
}

/** One step in a turn's 思考·正文·工具·协作 inline timeline (统一团队时间线).
 * reasoning/content/rework + tool are the CEO bubble's own narrative; the rest
 * are POSITIONAL MARKERS — zero-width anchors fixing WHERE a non-text element
 * renders (payload looked up from the turn's side channels by id). */
export type ProcessStep =
  | { kind: "reasoning"; text: string }
  | { kind: "content"; text: string }
  | { kind: "rework" }
  | { kind: "tool"; id: string; tool_name: string; arguments: Record<string, unknown>; result: string | null; status: "running" | "success" | "error"; display?: ToolDisplay | null; phase?: ToolPhase }
  | { kind: "team"; execution_id: string }
  | { kind: "checkpoint"; checkpoint_id: string }
  | { kind: "ask"; ask_id: string }
  | { kind: "plan_review"; checkpoint_id: string }
  | { kind: "team_preview"; checkpoint_id: string };

/** The user's settlement of a paused GRANTABLE tool call; mirrors the backend
 * `ApprovalDecision`. */
export type ApprovalDecision =
  | "approve"
  | "approve_always"
  | "approve_always_files"
  | "deny"
  | "orphaned";

export interface ApprovalRequiredPayload {
  approval_id: string;
  conversation_id: string;
  tool_call_id: string;
  tool_name: string;
  arguments: Record<string, unknown>;
}

export interface ApprovalResolvedPayload {
  approval_id: string;
  tool_call_id: string;
  decision: ApprovalDecision;
}

/** The user's settlement of a delegation-level authorization gate (委派级授权). */
export type DelegationAuthorizationDecision =
  | "grant_delegation"
  | "per_call"
  | "deny"
  | "orphaned";

/** One worker row on the delegation authorization card (role + task preview). */
export interface DelegationAuthorizationWorker {
  role: string;
  task: string;
}

/** A delegate batch paused awaiting the user's delegation-level tool authorization
 * (委派级授权). Medium-risk tools in `tools` are the grant scope. */
export interface DelegationAuthorizationRequiredPayload {
  authorization_id: string;
  conversation_id: string;
  execution_id: string;
  workers: DelegationAuthorizationWorker[];
  tools: string[];
}

export interface DelegationAuthorizationResolvedPayload {
  authorization_id: string;
  execution_id: string;
  decision: DelegationAuthorizationDecision;
}

/** The user's settlement of a checkpoint the CEO raised (ask_user). */
export type CheckpointDecision =
  | "continue"
  | "adjust"
  | "stop"
  | "timeout"
  | "orphaned";

export interface AskAssumption {
  id: string;
  label: string;
  value: string;
}

/** One selectable answer to a choice AskQuestion. `label` is both the displayed text
 * and the value composed back into the answer; `recommended` is advisory highlight only
 * (NOT a pre-selection). */
export interface AskOption {
  label: string;
  detail?: string;
  recommended?: boolean;
}

export interface AskQuestion {
  id: string;
  prompt: string;
  kind: "choice" | "text";
  options: AskOption[];
  multiple: boolean;
  default: string;
}

export interface AskStyleOption {
  id: string;
  label: string;
}

export type CheckpointIntent = "kickoff" | "decision";

/** The CEO paused the turn on an ask_user checkpoint (blocking). */
export interface CheckpointRequiredPayload {
  checkpoint_id: string;
  conversation_id: string;
  question: string;
  context: string;
  assumptions: AskAssumption[];
  questions: AskQuestion[];
  style_options: AskStyleOption[];
  intent?: CheckpointIntent;
}

export interface CheckpointResolvedPayload {
  checkpoint_id: string;
  decision: CheckpointDecision;
  note: string;
  selected?: string[];
}

/** A non-blocking ask the CEO posted (ask_user blocking=false): it already has a
 * default and KEPT WORKING — no suspend, no resolve. */
export interface QuestionPostedPayload {
  ask_id: string;
  conversation_id: string;
  question: string;
  context: string;
  assumptions: AskAssumption[];
  questions: AskQuestion[];
  style_options: AskStyleOption[];
}

export interface PlanReviewStep {
  run_id: string;
  role: string;
  summary: string;
}

export interface PlanReviewPending {
  run_id: string;
  role: string;
}

export interface PlanReviewRequiredPayload {
  checkpoint_id: string;
  conversation_id: string;
  steps: PlanReviewStep[];
  pending: PlanReviewPending[];
}

export interface PlanReviewResolvedPayload {
  checkpoint_id: string;
  decision: CheckpointDecision;
  note: string;
}

/** One upcoming worker row on the thin team-preview card (团队预审). */
export interface TeamPreviewWorker {
  run_id: string;
  role: string;
  task: string;
  depends_on: string[];
  debate: boolean;
}

export interface TeamPreviewRequiredPayload {
  checkpoint_id: string;
  conversation_id: string;
  workers: TeamPreviewWorker[];
}

export interface TeamPreviewResolvedPayload {
  checkpoint_id: string;
  decision: CheckpointDecision;
  note: string;
}

export type PlanRevisionKind = "bind" | "steer";

export interface PlanRevision {
  run_id: string;
  kind: PlanRevisionKind;
}

export interface PlanRevisedPayload {
  execution_id: string;
  revisions: PlanRevision[];
}

export interface PlanAgentPayload {
  id: string;
  role: string;
  model_preference: "fast" | "strong";
  thinking: boolean;
  reasoning_effort?: "high" | "max" | "low" | null;
}

export interface RunPlanRunEntry {
  id: string;
  agent_id: string;
  task: string;
  depends_on: string[];
  parent_run_id?: string;
  kind?: RunKind;
  stance?: Stance;
  group?: string;
  round?: number;
  replaces_run_id?: string;
}

export interface RunPlanPayload {
  execution_id: string;
  plan_type: "single_agent" | "multi_agent" | "debate";
  task_summary: string;
  agents: PlanAgentPayload[];
  runs: RunPlanRunEntry[];
}

export type RunKind = "captain" | "agent";

export type Stance = "pro" | "con";

export interface RunStartedPayload {
  run_id: string;
  agent_id: string;
  parent_run_id: string | null;
  kind: RunKind;
  revision?: number;
  stance?: Stance;
  group?: string;
  round?: number;
  replaces_run_id?: string;
}

export interface ContextBlockWire {
  channel: "system" | "history" | "request" | "team_position" | "dependency" | "workspace" | "task" | "deliverable" | "team_brief" | "steer" | "team_result" | "round_focus" | "opponent" | "challenge" | "interjection" | "revision" | "cross_exam" | "closing";
  heading: string;
  body: string;
  chars: number;
  truncated: boolean;
  source_role: string;
  source_run_id: string;
  fidelity: "" | "pointer" | "summarize" | "pass_through";
  files: string[];
}

export interface RunContextPayload {
  run_id: string;
  agent_id: string;
  blocks: ContextBlockWire[];
}

export interface RunOutputDeltaPayload {
  run_id: string;
  agent_id: string;
  delta: string;
}

export interface RunOutputResetPayload {
  run_id: string;
  agent_id: string;
}

export interface RunReasoningDeltaPayload {
  run_id: string;
  agent_id: string;
  delta: string;
}

export interface RunToolProgressPayload {
  run_id: string;
  agent_id: string;
  tool_name: string;
  chars: number;
}

export type EscalationKind = "normal" | "scope" | "dep";

export interface RunEscalationPayload {
  run_id: string;
  agent_id: string;
  question: string;
  assumption: string;
  blocking: boolean;
  kind?: EscalationKind;
}

export interface RunIntakePayload {
  run_id: string;
  agent_id: string;
  complexity: "simple" | "moderate" | "complex";
  strategy: "direct_execute" | "needs_tools" | "needs_research";
  token_budget: number;
  rationale?: string;
  signals?: string[];
}

export interface RunEscalationGatePayload {
  run_id: string;
  agent_id: string;
  layer: "execution" | "scheme";
  action: "continue" | "escalate";
  signals: Record<string, unknown>[];
}

/** 阻塞式求决策 (escalate blocking=true): a delegated worker SUSPENDED itself awaiting
 * a decision. JOURNALED (unlike the transport-only `run_escalation` banner); the
 * turn never flips to `paused` (siblings keep running).
 * 
 * ``awaiting``: ``user`` (经典路径，可答卡) or ``ceo`` (协调模式下等主管仲裁，初始不可答)。
 * Absent on old journaled events → fold as ``user``. */
export interface EscalationRequiredPayload {
  escalation_id: string;
  run_id: string;
  agent_id: string;
  question: string;
  assumption: string;
  /** Structured forks (同 ask_user 的 questions). Absent on old journaled events (fold with `?? []`); empty for a free-text ask. */
  questions?: AskQuestion[];
  /** 旧流缺字段时前端按 `normal`。与 blocking 轴正交。 */
  kind?: EscalationKind;
  /** 谁在仲裁：user=经典可答卡；ceo=协调模式等主管。旧流缺字段按 user。 */
  awaiting?: "user" | "ceo";
}

/** 阻塞式求决策 settlement. Emitted by the suspending tool's awaiter ONLY; journaled.
 * 
 * ``status`` 三分（对 worker 回落假设的实现可共享，对外语义必须分开）：
 * - ``resolved`` — 有裁决/答复（``answer`` 非空语义由调用方保证）
 * - ``assumed`` — 用户或主管显式选了「按假设继续」
 * - ``timed_out`` — 墙钟时限内未答复
 * 
 * ``arbitrated_by`` / ``via_user`` annotate CEO 协调仲裁可见性（经典用户直答路径可缺省）。 */
export interface EscalationResolvedPayload {
  escalation_id: string;
  run_id: string;
  agent_id: string;
  status: "resolved" | "assumed" | "timed_out" | "orphaned";
  answer: string;
  /** 裁决方：user=用户直答；ceo=主管仲裁。旧流缺字段按 user。 */
  arbitrated_by?: "user" | "ceo";
  /** 仅 arbitrated_by=ceo 时有意义：true=主管经 ask_user 转交用户后再 resolve。 */
  via_user?: boolean;
}

/** 热路 pending 交互失效（假卡消灭）。kind ∈ 热路四 kind。 */
export interface InteractionOrphanedPayload {
  interaction_id: string;
  kind: "approval" | "delegation_authorization" | "escalation" | "debate_round";
}

export interface TeamNotePostedPayload {
  execution_id: string;
  note_id: string;
  run_id: string;
  agent_id: string;
  role: string;
  kind: "decision" | "heads_up" | "claim";
  text: string;
  ts: number;
  supersedes?: string;
  supersede_mode?: "update" | "void";
  source?: "ceo" | "worker" | "inherited";
}

export interface TeamSynthesisWorkerPreview {
  run_id: string;
  role: string;
  status: "pending" | "completed" | "failed" | "cancelled";
  summary: string;
}

export interface TeamSynthesisPreviewPayload {
  execution_id: string;
  completed: number;
  total: number;
  headline: string;
  text: string;
  workers: TeamSynthesisWorkerPreview[];
  in_progress: boolean;
}

/** Token counts in the ledger short-key form. `cache_hit + cache_miss === input`. */
export interface UsageBreakdown {
  input: number;
  output: number;
  reasoning: number;
  cache_hit: number;
  cache_miss: number;
}

/** A run's / turn's cost in integer nano-USD (1 USD = 1e9). */
export interface CostBreakdown {
  input: number;
  cached: number;
  output: number;
  total: number;
  currency: string;
}

/** 完工交接简报 — every field optional; absent when the worker did not call `handoff`. */
export interface RunDebrief {
  summary?: string | null;
  key_points?: string[] | null;
  assumptions?: string | null;
  next_steps?: string | null;
}

export interface RunCompletedPayload {
  run_id: string;
  agent_id: string;
  output_summary: string;
  duration_ms: number;
  role: string;
  model: string;
  usage: UsageBreakdown;
  cost: CostBreakdown;
  debrief?: RunDebrief;
  output_files?: string[];
}

export interface RunFailedPayload {
  run_id: string;
  agent_id: string;
  error: string;
  debrief?: RunDebrief;
}

export interface RunCancelledPayload {
  run_id: string;
  agent_id: string;
  reason: "redirect" | "stop";
}

export interface RunProgressPayload {
  completed: number;
  total: number;
}

export interface NodeTimingPayload {
  run_id: string;
  start_ms: number;
  end_ms: number;
  outcome: string;
}

export interface BatchMetricsPayload {
  execution_id: string;
  nodes: number;
  width: number;
  peak_running: number;
  wall_ms: number;
  busy_ms: number;
  slot_starved: number;
  completed: number;
  failed: number;
  skipped: number;
  cancelled: number;
  bind_boundaries: number;
  scope_boundaries: number;
  checkpoint_boundaries: number;
  escalations: number;
  scope_escalations: number;
  timeline: NodeTimingPayload[];
}

export interface DebateSideInfo {
  key: string;
  name: string;
  stance: string;
  is_subject: boolean;
  /** Display-only model hint on some debate forms; absent on older wire. */
  model?: string;
}

export interface DebateRoundSide {
  key: string;
  name: string;
  run_id: string;
  ok: boolean;
}

export interface DebateVerdict {
  real_clash: boolean;
  new_arguments: boolean;
  converged: boolean;
  stop_reason: string;
  rationale: string;
}

export interface DebateClash {
  from_key: string;
  to_key: string;
  point: string;
}

export interface DebateUserInterjection {
  ask: string;
  target_key: string;
  answered: boolean;
}

export interface DebateCrossExamExchange {
  question: string;
  answer: string;
  ok: boolean;
}

export interface DebateCrossExam {
  target: string;
  questioner: string;
  exchanges: DebateCrossExamExchange[];
  answer_run_id: string;
}

export interface DebateClosing {
  key: string;
  name: string;
  run_id: string;
  ok: boolean;
}

export interface DebateRoundScore {
  argument: number;
  engagement: number;
  evidence: number;
  penalties: string[];
  note: string;
  total: number;
}

export interface DebateRoundInfo {
  round_no: number;
  focus: string;
  summary: string;
  verdict: DebateVerdict;
  sides: DebateRoundSide[];
  clashes: DebateClash[];
  user_interjections?: DebateUserInterjection[];
  cross_exam?: DebateCrossExam[];
  scores?: Record<string, DebateRoundScore>;
}

export interface DebateNarrativeRound {
  round_no: number;
  focus: string;
  summary: string;
  verdict: DebateVerdict | null;
  sides: DebateRoundSide[];
  clashes: DebateClash[];
  cross_exam: DebateCrossExam[];
}

export interface DebateBriefInfo {
  crux: string;
  strongest_points: Record<string, string>;
  risk_severities?: Record<string, string>;
  factual_disputes: string[];
  value_disputes: string[];
  decisive?: string;
  leaning: string;
  confidence: string;
  recommendation: string;
  open_questions: string[];
}

export interface DebateResultPayload {
  execution_id: string;
  moderator_run_id: string;
  form: "debate" | "red_team" | "roundtable";
  motion: string;
  stop_reason: string;
  opening?: string;
  narrative_first: boolean;
  sides: DebateSideInfo[];
  rounds: DebateRoundInfo[];
  closings?: DebateClosing[];
  brief: DebateBriefInfo;
}

export interface DebateRoundStartedPayload {
  execution_id: string;
  moderator_run_id: string;
  round_no: number;
  focus: string;
}

export interface DebateRoundPayload extends DebateRoundInfo {
  execution_id: string;
  moderator_run_id: string;
}

export interface DebateRoundDecisionRequiredPayload {
  execution_id: string;
  moderator_run_id: string;
  decision_id: string;
  round_no: number;
  focus: string;
  summary: string;
  converged: boolean;
  rationale: string;
}

export interface DebateRoundDecisionResolvedPayload {
  execution_id: string;
  moderator_run_id: string;
  decision_id: string;
  decision: "continue" | "conclude" | "timeout" | "orphaned";
  focus: string;
}

/** 协作质量: turn-level orchestration signals for 诊断模式. Omitted on single-agent
 * turns and legacy streams. */
export interface TurnCollabMetrics {
  boundary_yields: number;
  scope_signals: number;
  revises: number;
  escalations: number;
  /** 审计采集降级计数 (turn_metrics.audit_drops); 诊断模式 only. */
  audit_drops?: number;
}

/** Turn token totals (long-key form, contrast `UsageBreakdown` short keys on runs). */
export interface MessageEndUsage {
  input_tokens: number;
  output_tokens: number;
  reasoning_tokens: number;
  cache_hit_tokens: number;
  cache_miss_tokens: number;
}

/** Terminal turn event. `finish_reason=paused` = 挂起即收口: the turn finalized AT a
 * durable checkpoint and awaits POST .../resume — NOT done and not aborted. */
export interface MessageEndPayload {
  finish_reason: "end_turn" | "max_rounds" | "degraded" | "unproductive" | "error" | "cancelled" | "interrupted" | "paused";
  usage?: MessageEndUsage;
  cost?: CostBreakdown;
  rounds?: number;
  collab?: TurnCollabMetrics;
}

export interface ErrorContext {
  upstream_status?: number;
  upstream_body_preview?: string | null;
  retry_attempts?: number;
  empty_diagnosis?: string;
}

export interface ErrorPayload {
  code: string;
  message: string;
  context?: ErrorContext;
}

export interface TitleGeneratedPayload {
  conversation_id: string;
  title: string;
  /** Conversation auto-tag minted with the title; present only when classified. */
  tag?: string;
}

/** BYOK soft gate: preflight hint when probe says the user's model may lack tool
 * calling. Transport-only — not journaled. */
export interface TurnWarningPayload {
  message: string;
}

/** 3D position on the town ground plane (Y-up wire coordinates).
 * 
 * - ``x``: east (+) / west (-)
 * - ``y``: height above ground (NPCs typically 0)
 * - ``z``: south (+) / north (-) */
export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

/** Per-agent snapshot on `sim.agent_state` and in tick snapshots. */
export interface SimAgentState {
  agent_id: string;
  name: string;
  role: string;
  location: string;
  position: Vec3;
  activity: string;
  mood: number;
  goal: string;
  last_thought: string;
  relationships?: Record<string, number>;
  tick_memories?: string[];
  money?: number;
  inventory?: Record<string, number>;
}

/** One agent decision within a tick (`sim.agent_action`). */
export interface SimAgentAction {
  agent_id: string;
  action: "move_to" | "stay_here" | "speak_to" | "propose_trade" | "propose_vote" | "idle" | "error";
  thought: string;
  tool_name?: string | null;
  tool_args?: Record<string, unknown> | null;
  success: boolean;
  detail: string;
}

export interface SimTickStartedPayload {
  run_id: string;
  tick: number;
  hour: number;
}

/** Macro indicators for one simulation tick (backend `TickMetrics`), carried on
 * `sim.tick_ended` for the 观测面板. `population_by_region` maps a region name →
 * head count. */
export interface SimTickMetrics {
  tick: number;
  hour: number;
  avg_mood: number;
  trade_count: number;
  trade_total_amount: number;
  positive_relation_ratio: number;
  population_by_region: Record<string, number>;
}

export interface SimTickEndedPayload {
  run_id: string;
  tick: number;
  hour: number;
  agent_count: number;
  metrics?: SimTickMetrics | null;
}

/** One persisted world frame on tick replay (``simulation/service.py`` replay path).
 * `snapshot` is the verbatim ``SimTickSnapshot`` dump persisted on the tick row. */
export interface SimTickFramePayload {
  run_id: string;
  tick_number: number;
  snapshot: Record<string, unknown>;
}

export interface SimAgentStatePayload {
  run_id: string;
  tick: number;
  state: SimAgentState;
}

export interface SimAgentActionPayload {
  run_id: string;
  tick: number;
  action: SimAgentAction;
}

export interface InteractionTranscriptLine {
  speaker_id: string;
  speaker_name: string;
  text: string;
  round: number;
}

/** Summary of world mutations applied by an interaction. */
export interface InteractionStateChange {
  mood_deltas?: Record<string, number>;
  relation_deltas?: [string, string, number][];
  money_transfers?: Record<string, unknown>[];
  inventory_transfers?: Record<string, unknown>[];
  governance?: Record<string, unknown>;
}

export interface InteractionResult {
  request_id: string;
  kind: "conversation" | "trade" | "vote";
  status: "completed" | "rejected" | "failed" | "cancelled";
  initiator_id: string;
  target_id?: string | null;
  summary: string;
  transcript?: InteractionTranscriptLine[];
  state_changes?: InteractionStateChange;
  detail?: string;
}

/** Structured interaction result on ``sim.interaction``. */
export interface SimInteractionPayload {
  run_id: string;
  tick: number;
  interaction: InteractionResult;
}

/** World-level knobs affected by scheduled events. */
export interface WorldModifiersWire {
  market_price_multiplier: number;
  storm_active: boolean;
  festival_active: boolean;
  square_attraction_boost: number;
}

/** One active world event in tick snapshots. */
export interface WorldEventWire {
  event_id: string;
  kind: string;
  event_type: string;
  title: string;
  description: string;
  payload?: Record<string, unknown>;
  tick_started: number;
  duration_ticks: number;
  source: string;
}

/** ``sim.world_event`` SSE + sim_event row. */
export interface SimWorldEventPayload {
  run_id: string;
  tick: number;
  event: WorldEventWire;
  modifiers: WorldModifiersWire;
}

/** CEO→用户「下一步推荐」: 2-4 quick-reply chips for the just-finished turn, emitted
 * after `message_end`. Persisted on `Message.followups` (DERIVED), no-op in folds.
 * `message_id` is the assistant row the chips belong to (same id as `set_followups`). */
export interface FollowupsGeneratedPayload {
  conversation_id: string;
  message_id: string;
  followups: string[];
}

export interface TurnSavedPayload {
  user_message_id: string;
}

export interface Citation {
  url: string;
  title: string;
  snippet?: string;
  site?: string;
}

export interface CitationsPayload {
  citations: Citation[];
}

/** Transport-only client-tool request: apply a workspace file op on the bound
 * desktop and POST the result back. NOT journaled. */
export interface WorkspaceOpRequiredPayload {
  request_id: string;
  conversation_id: string;
  root_id: string;
  op: string;
  args: Record<string, unknown>;
}

/** One structured whiteboard op (AI协作白板 M2). The closed verb set is shared with
 * the server tool + the desktop applier; fields beyond `op` are op-specific. */
export interface BoardOp {
  op: "add_node" | "connect" | "move" | "set_text" | "delete" | "group";
  ref?: string;
  id?: string;
  kind?: "sticky" | "rectangle" | "ellipse" | "diamond" | "text";
  text?: string;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  color?: string;
  from?: string;
  to?: string;
  label?: string;
  members?: string[];
}

/** Transport-only client-tool request: apply a batch of board ops to the open
 * whiteboard canvas (`board_id`). The board counterpart of `workspace_op_required`;
 * NOT journaled. */
export interface BoardOpRequiredPayload {
  request_id: string;
  conversation_id: string;
  board_id: string;
  ops: BoardOp[];
  summary: string;
}

/** Transport-only client-tool request: rasterize board elements (`ids`) to a PNG and
 * POST it back so the vision reader can read it. NOT journaled. */
export interface BoardReadRequiredPayload {
  request_id: string;
  conversation_id: string;
  board_id: string;
  ids: string[];
}

/** Transport-only client-tool request: show an OS notification on the bound desktop
 * (`desktop_notify` worker tool). NOT journaled. */
export interface DesktopNotifyRequiredPayload {
  request_id: string;
  conversation_id: string;
  title: string;
  body?: string;
}

export interface HandoffSnapshotDonePayload {
  snapshot_id: string;
  conversation_id: string;
  size_bytes: number;
}

export interface HandoffJobStartedPayload {
  job_id: string;
  conversation_id: string;
  job_conversation_id: string;
}

export interface HandoffApplyResult {
  path: string;
  status: "applied" | "skipped" | "conflict" | "error";
  change_type: "added" | "modified" | "deleted" | null;
  detail: string;
}

export interface HandoffApplyDonePayload {
  job_id: string;
  conversation_id: string;
  results: HandoffApplyResult[];
  applied: number;
  skipped: number;
  conflicts: number;
  errors: number;
}

export type SSEPayloadMap = {
  message_start: MessageStartPayload;
  content_delta: ContentDeltaPayload;
  content_reset: ContentResetPayload;
  reasoning_delta: ReasoningDeltaPayload;
  tool_progress: ToolProgressPayload;
  tool_use_progress: ToolUseProgressPayload;
  tool_use_start: ToolUseStartPayload;
  tool_use_end: ToolUseEndPayload;
  approval_required: ApprovalRequiredPayload;
  approval_resolved: ApprovalResolvedPayload;
  delegation_authorization_required: DelegationAuthorizationRequiredPayload;
  delegation_authorization_resolved: DelegationAuthorizationResolvedPayload;
  checkpoint_required: CheckpointRequiredPayload;
  checkpoint_resolved: CheckpointResolvedPayload;
  question_posted: QuestionPostedPayload;
  plan_review_required: PlanReviewRequiredPayload;
  plan_review_resolved: PlanReviewResolvedPayload;
  team_preview_required: TeamPreviewRequiredPayload;
  team_preview_resolved: TeamPreviewResolvedPayload;
  plan_revised: PlanRevisedPayload;
  run_plan: RunPlanPayload;
  run_started: RunStartedPayload;
  run_context: RunContextPayload;
  run_output_delta: RunOutputDeltaPayload;
  run_output_reset: RunOutputResetPayload;
  run_reasoning_delta: RunReasoningDeltaPayload;
  run_tool_progress: RunToolProgressPayload;
  run_completed: RunCompletedPayload;
  run_failed: RunFailedPayload;
  run_cancelled: RunCancelledPayload;
  run_progress: RunProgressPayload;
  batch_metrics: BatchMetricsPayload;
  run_escalation: RunEscalationPayload;
  run_intake: RunIntakePayload;
  run_escalation_gate: RunEscalationGatePayload;
  escalation_required: EscalationRequiredPayload;
  escalation_resolved: EscalationResolvedPayload;
  interaction_orphaned: InteractionOrphanedPayload;
  team_note_posted: TeamNotePostedPayload;
  team_synthesis_preview: TeamSynthesisPreviewPayload;
  debate_result: DebateResultPayload;
  debate_round_started: DebateRoundStartedPayload;
  debate_round: DebateRoundPayload;
  debate_round_decision_required: DebateRoundDecisionRequiredPayload;
  debate_round_decision_resolved: DebateRoundDecisionResolvedPayload;
  message_end: MessageEndPayload;
  error: ErrorPayload;
  title_generated: TitleGeneratedPayload;
  turn_warning: TurnWarningPayload;
  "sim.tick_started": SimTickStartedPayload;
  "sim.tick_ended": SimTickEndedPayload;
  "sim.tick_frame": SimTickFramePayload;
  "sim.agent_action": SimAgentActionPayload;
  "sim.agent_state": SimAgentStatePayload;
  "sim.interaction": SimInteractionPayload;
  "sim.world_event": SimWorldEventPayload;
  followups_generated: FollowupsGeneratedPayload;
  turn_saved: TurnSavedPayload;
  citations: CitationsPayload;
  workspace_op_required: WorkspaceOpRequiredPayload;
  board_op_required: BoardOpRequiredPayload;
  board_read_required: BoardReadRequiredPayload;
  desktop_notify_required: DesktopNotifyRequiredPayload;
  handoff_snapshot_done: HandoffSnapshotDonePayload;
  handoff_job_started: HandoffJobStartedPayload;
  handoff_apply_done: HandoffApplyDonePayload;
};
