// AUTO-GENERATED by apps/server/scripts/dump_interaction_kinds.py — do not edit.
// Single source: agentcore.runtime.interaction.InteractionKind + INTERACTION_KIND_SPECS
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_interaction_kinds.py)

/** Full bridge enum (includes client_tool). */
export type InteractionKind =
  | "approval"
  | "ask_user"
  | "client_tool"
  | "delegation_authorization"
  | "escalation"
  | "plan_review"
  | "question_posted"
  | "stage_card"
  | "team_preview";

export const INTERACTION_KIND_VALUES = [
  "approval",
  "ask_user",
  "client_tool",
  "delegation_authorization",
  "escalation",
  "plan_review",
  "question_posted",
  "stage_card",
  "team_preview",
] as const;

/** User-facing decision / ask kinds (InteractionStore + journal fold). */
export type UserInteractionKind =
  | "approval"
  | "ask_user"
  | "delegation_authorization"
  | "escalation"
  | "plan_review"
  | "question_posted"
  | "stage_card"
  | "team_preview";

export const USER_INTERACTION_KIND_VALUES = [
  "approval",
  "ask_user",
  "delegation_authorization",
  "escalation",
  "plan_review",
  "question_posted",
  "stage_card",
  "team_preview",
] as const;

export type InteractionKindWire = {
  readonly requiredEvent: string;
  readonly resolvedEvent: string | null;
  readonly idField: string;
};

/** kind → SSE required/resolved event names + payload id field. */
export const INTERACTION_KIND_WIRE: Readonly<Record<UserInteractionKind, InteractionKindWire>> = {
  "approval": {
    requiredEvent: "approval_required",
    resolvedEvent: "approval_resolved",
    idField: "approval_id",
  },
  "ask_user": {
    requiredEvent: "checkpoint_required",
    resolvedEvent: "checkpoint_resolved",
    idField: "checkpoint_id",
  },
  "delegation_authorization": {
    requiredEvent: "delegation_authorization_required",
    resolvedEvent: "delegation_authorization_resolved",
    idField: "authorization_id",
  },
  "escalation": {
    requiredEvent: "escalation_required",
    resolvedEvent: "escalation_resolved",
    idField: "escalation_id",
  },
  "plan_review": {
    requiredEvent: "plan_review_required",
    resolvedEvent: "plan_review_resolved",
    idField: "checkpoint_id",
  },
  "question_posted": {
    requiredEvent: "question_posted",
    resolvedEvent: "question_resolved",
    idField: "ask_id",
  },
  "stage_card": {
    requiredEvent: "stage_card_required",
    resolvedEvent: "stage_card_resolved",
    idField: "stage_card_id",
  },
  "team_preview": {
    requiredEvent: "team_preview_required",
    resolvedEvent: "team_preview_resolved",
    idField: "checkpoint_id",
  },
};
