/*
 * Precompute the demo DAG's ELK coordinates → src/data/layout.ts.
 *
 * Reuses the REAL desktop computeLayout (incl. its endpoint-centering and
 * sub-team post-processing) via a relative import — elk-layout.ts only imports
 * `elkjs` at runtime (its `@/stores/graph` import is type-only, erased by tsx),
 * so this runs under `npx tsx` with elkjs resolved from apps/promo/node_modules.
 *
 * Run:  npx tsx scripts/precompute-layout.mts   (cwd = apps/promo)
 *
 * Baking coordinates to a constant keeps render-time fully synchronous and
 * deterministic (the demo shape is fixed), per apps/promo/README.md.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { computeLayout } from "../../desktop/src/renderer/lib/elk-layout";
import {
  CAPTAIN_ID,
  DEMO_LAYOUT_EDGES,
  DEMO_NODE_IDS,
  INPUT_ID,
} from "../src/data/demo";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, "../src/data/layout.ts");

// Left-right layered flow (product default, widescreen); considerModelOrder (always
// on in computeLayout) bands the debate 正/反 (激进方案 above, 稳健方案 below);
// bookends pin input first / captain last.
const LAYOUT = "leftright" as const;

async function main(): Promise<void> {
  const result = await computeLayout(
    DEMO_NODE_IDS,
    DEMO_LAYOUT_EDGES,
    LAYOUT,
    { source: INPUT_ID, sink: CAPTAIN_ID },
  );

  const positions = Object.fromEntries(
    Object.entries(result.positions).map(([id, p]) => [
      id,
      { x: round(p.x), y: round(p.y) },
    ]),
  );

  const body = `/*
 * AUTO-GENERATED by scripts/precompute-layout.mts — do not edit by hand.
 * Re-run \`npx tsx scripts/precompute-layout.mts\` after changing the demo DAG.
 *
 * Baked ELK coordinates for the demo butterfly DAG (layout="${LAYOUT}"), so the
 * promo renders the collaboration graph with zero async layout at frame time.
 */

export interface DemoLayout {
  positions: Record<string, { x: number; y: number }>;
  width: number;
  height: number;
}

export const DEMO_LAYOUT: DemoLayout = ${JSON.stringify(
    { positions, width: round(result.width), height: round(result.height) },
    null,
    2,
  )};
`;

  await writeFile(OUT, body, "utf8");

  console.log(`✓ wrote ${path.relative(process.cwd(), OUT)}`);
  console.log(
    `  bbox ${round(result.width)}×${round(result.height)}, ${
      Object.keys(positions).length
    } nodes`,
  );
  for (const [id, p] of Object.entries(positions)) {
    console.log(`  ${id.padEnd(16)} (${p.x}, ${p.y})`);
  }
}

function round(n: number): number {
  return Math.round(n * 100) / 100;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
