/*
 * Precompute ELK coordinates for the 9 promo STILL scenarios → src/data/stillsLayout.ts.
 *
 * Reuses the REAL desktop computeLayout (incl. its endpoint-centering, sub-team
 * drop and revision-alignment post-processing) via a relative import — elk-layout.ts
 * only imports `elkjs` at runtime (its `@/stores/graph` import is type-only, erased
 * by tsx), so this runs under `npx tsx` with elkjs resolved from apps/promo/node_modules.
 *
 * Run:  npx tsx scripts/precompute-stills-layout.mts   (cwd = apps/promo)
 *
 * Baking coordinates to a constant keeps render-time fully synchronous and
 * deterministic, matching the existing demo-butterfly precompute (see
 * scripts/precompute-layout.mts).
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { computeLayout } from "../../desktop/src/renderer/lib/elk-layout";
import { STILL_DEFS } from "../src/data/stills";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, "../src/data/stillsLayout.ts");

const INPUT_ID = "__input__";
const CAPTAIN_ID = "captain";

function round(n: number): number {
  return Math.round(n * 100) / 100;
}

interface BakedLayout {
  positions: Record<string, { x: number; y: number }>;
  width: number;
  height: number;
}

async function main(): Promise<void> {
  const out: Record<string, BakedLayout> = {};

  for (const def of STILL_DEFS) {
    const ids = def.nodes.map((n) => n.id);
    // Debate banding: preserveOrder bands 正方 above 反方 (same trigger as the
    // manual's EmbeddedGraphCanvas — any node carrying a `stance`).
    const debate = def.nodes.some(
      (n) => (n.data as { stance?: string }).stance != null,
    );
    const result = await computeLayout(
      ids,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      def.edges as any,
      def.layout,
      debate,
      { source: INPUT_ID, sink: CAPTAIN_ID },
    );

    out[def.id] = {
      positions: Object.fromEntries(
        Object.entries(result.positions).map(([id, p]) => [
          id,
          { x: round(p.x), y: round(p.y) },
        ]),
      ),
      width: round(result.width),
      height: round(result.height),
    };
    console.log(
      `  ${def.id.padEnd(10)} ${round(result.width)}×${round(result.height)}  (${ids.length} nodes${debate ? ", debate" : ""})`,
    );
  }

  const body = `/*
 * AUTO-GENERATED by scripts/precompute-stills-layout.mts — do not edit by hand.
 * Re-run \`npx tsx scripts/precompute-stills-layout.mts\` after changing STILL_DEFS.
 *
 * Baked ELK coordinates (+ bbox) for each promo still scenario, keyed by id, so
 * the stills render with zero async layout and are layout-identical to the manual.
 */

export interface StillLayoutResult {
  positions: Record<string, { x: number; y: number }>;
  width: number;
  height: number;
}

export const STILLS_LAYOUT: Record<string, StillLayoutResult> = ${JSON.stringify(
    out,
    null,
    2,
  )};
`;

  await writeFile(OUT, body, "utf8");
  console.log(`✓ wrote ${path.relative(process.cwd(), OUT)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
