/*
 * Precompute the sample hero DAG ELK coordinates → src/kit/hero/layout.ts.
 *
 * Uses `@agentcore/graph-layout` (same computeLayout as desktop).
 *
 * Run:  pnpm layout   (cwd = apps/promo)
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { computeLayout } from "@agentcore/graph-layout";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(__dirname, "../src/kit/hero");
const OUT = path.join(dataDir, "layout.ts");
const LAYOUT = "leftright" as const;

async function main(): Promise<void> {
  const {
    CAPTAIN_ID,
    DEMO_LAYOUT_EDGES,
    DEMO_NODE_IDS,
    INPUT_ID,
  } = await import("../src/kit/hero/demo.ts");

  const result = await computeLayout(
    DEMO_NODE_IDS,
    DEMO_LAYOUT_EDGES,
    LAYOUT,
    { source: INPUT_ID, sink: CAPTAIN_ID },
  );

  const positions = Object.fromEntries(
    Object.entries(result.positions).map(([id, p]) => [
      id,
      { x: round(p.x), y: round(p.y) },
    ]),
  );

  const body = `/*
 * AUTO-GENERATED by scripts/precompute-layout.mts — do not edit by hand.
 * Re-run \`pnpm layout\` after changing the sample DAG in src/kit/hero/demo.ts.
 *
 * Baked ELK coordinates (layout="${LAYOUT}"), so promo stills render with
 * zero async layout at frame time.
 */

export interface DemoLayout {
  positions: Record<string, { x: number; y: number }>;
  width: number;
  height: number;
}

export const DEMO_LAYOUT: DemoLayout = ${JSON.stringify(
    { positions, width: round(result.width), height: round(result.height) },
    null,
    2,
  )};
`;

  await writeFile(OUT, body, "utf8");

  console.log(`✓ wrote ${path.relative(process.cwd(), OUT)}`);
  console.log(
    `  bbox ${round(result.width)}×${round(result.height)}, ${
      Object.keys(positions).length
    } nodes`,
  );
  for (const [id, p] of Object.entries(positions)) {
    console.log(`  ${id.padEnd(16)} (${p.x}, ${p.y})`);
  }
}

function round(n: number): number {
  return Math.round(n * 100) / 100;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
