/*
 * AUTO-GENERATED by scripts/precompute-stills-layout.mts — do not edit by hand.
 * Re-run `pnpm stills:layout` after changing STILL_DEFS.
 *
 * Baked ELK coordinates (+ bbox) for each promo still scenario, keyed by id, so
 * the stills render with zero async layout and are layout-identical to the manual.
 */

export interface StillLayoutResult {
  positions: Record<string, { x: number; y: number }>;
  width: number;
  height: number;
}

export const STILLS_LAYOUT: Record<string, StillLayoutResult> = {
  "fanout": {
    "positions": {
      "__input__": {
        "x": 24,
        "y": 190
      },
      "w1": {
        "x": 314,
        "y": 24
      },
      "w2": {
        "x": 314,
        "y": 190
      },
      "w3": {
        "x": 314,
        "y": 356
      },
      "captain": {
        "x": 604,
        "y": 190
      }
    },
    "width": 838,
    "height": 490
  },
  "debate": {
    "positions": {
      "__input__": {
        "x": 24,
        "y": 273
      },
      "mod": {
        "x": 314,
        "y": 273
      },
      "pro1": {
        "x": 604,
        "y": 24
      },
      "pro2": {
        "x": 604,
        "y": 190
      },
      "con1": {
        "x": 604,
        "y": 356
      },
      "con2": {
        "x": 604,
        "y": 522
      },
      "captain": {
        "x": 894,
        "y": 273
      }
    },
    "width": 1128,
    "height": 656
  },
  "nested2": {
    "positions": {
      "__input__": {
        "x": 24,
        "y": 148.67
      },
      "mpm": {
        "x": 314,
        "y": 148.67
      },
      "lead": {
        "x": 604,
        "y": 107
      },
      "eng1": {
        "x": 894,
        "y": 24
      },
      "eng2": {
        "x": 894,
        "y": 190
      },
      "captain": {
        "x": 1184,
        "y": 148.67
      }
    },
    "width": 1418,
    "height": 324
  },
  "bigteam": {
    "positions": {
      "__input__": {
        "x": 24,
        "y": 356
      },
      "m1": {
        "x": 314,
        "y": 24
      },
      "m2": {
        "x": 314,
        "y": 190
      },
      "m3": {
        "x": 314,
        "y": 356
      },
      "m4": {
        "x": 314,
        "y": 522
      },
      "m5": {
        "x": 314,
        "y": 688
      },
      "pm": {
        "x": 604,
        "y": 356
      },
      "mod": {
        "x": 894,
        "y": 356
      },
      "pro1": {
        "x": 1184,
        "y": 163
      },
      "pro2": {
        "x": 1184,
        "y": 329
      },
      "con1": {
        "x": 1184,
        "y": 495
      },
      "con2": {
        "x": 1184,
        "y": 661
      },
      "decide": {
        "x": 1474,
        "y": 356
      },
      "pd": {
        "x": 1764,
        "y": 249.67
      },
      "arch": {
        "x": 1764,
        "y": 546.67
      },
      "ix": {
        "x": 2054,
        "y": 101.17
      },
      "vd": {
        "x": 2054,
        "y": 267.17
      },
      "be": {
        "x": 2054,
        "y": 398.17
      },
      "dm": {
        "x": 2054,
        "y": 564.17
      },
      "captain": {
        "x": 2344,
        "y": 398.17
      }
    },
    "width": 2578,
    "height": 822
  },
  "bigteam-tall": {
    "positions": {
      "__input__": {
        "x": 556,
        "y": 24
      },
      "m1": {
        "x": 24,
        "y": 198
      },
      "m2": {
        "x": 290,
        "y": 198
      },
      "m3": {
        "x": 556,
        "y": 198
      },
      "m4": {
        "x": 822,
        "y": 198
      },
      "m5": {
        "x": 1088,
        "y": 198
      },
      "pm": {
        "x": 556,
        "y": 372
      },
      "mod": {
        "x": 556,
        "y": 546
      },
      "pro1": {
        "x": 243,
        "y": 720
      },
      "pro2": {
        "x": 509,
        "y": 720
      },
      "con1": {
        "x": 775,
        "y": 720
      },
      "con2": {
        "x": 1041,
        "y": 720
      },
      "decide": {
        "x": 556,
        "y": 894
      },
      "pd": {
        "x": 383,
        "y": 1068
      },
      "arch": {
        "x": 880,
        "y": 1068
      },
      "ix": {
        "x": 134.5,
        "y": 1242
      },
      "vd": {
        "x": 400.5,
        "y": 1242
      },
      "be": {
        "x": 631.5,
        "y": 1242
      },
      "dm": {
        "x": 897.5,
        "y": 1242
      },
      "captain": {
        "x": 631.5,
        "y": 1416
      }
    },
    "width": 1322,
    "height": 1550
  }
};
