/*
 * Precompute ELK coordinates for the promo STILL scenarios → src/stills/data/stillsLayout.ts.
 *
 * Uses `@agentcore/graph-layout` (same computeLayout as desktop; no relative
 * import into apps/desktop). Runtime deps are packagable (elkjs + pure helpers).
 *
 * Run:  pnpm stills:layout   (cwd = apps/video)
 *
 * Baking coordinates to a constant keeps render-time fully synchronous and
 * deterministic, matching the video-package precompute (see
 * scripts/precompute-layout.mts).
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { computeLayout } from "@agentcore/graph-layout";
import { STILL_DEFS } from "../src/stills/data/stills";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, "../src/stills/data/stillsLayout.ts");

const INPUT_ID = "__input__";
const CAPTAIN_ID = "captain";

function round(n: number): number {
  return Math.round(n * 100) / 100;
}

interface BakedLayout {
  positions: Record<string, { x: number; y: number }>;
  width: number;
  height: number;
}

async function main(): Promise<void> {
  const out: Record<string, BakedLayout> = {};

  for (const def of STILL_DEFS) {
    const ids = def.nodes.map((n) => n.id);
    // Debate banding is now always on (considerModelOrder inside computeLayout),
    // so a node carrying a `stance` bands 正方 above 反方 without a caller flag.
    const result = await computeLayout(
      ids,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      def.edges as any,
      def.layout,
      { source: INPUT_ID, sink: CAPTAIN_ID },
    );

    out[def.id] = {
      positions: Object.fromEntries(
        Object.entries(result.positions).map(([id, p]) => [
          id,
          { x: round(p.x), y: round(p.y) },
        ]),
      ),
      width: round(result.width),
      height: round(result.height),
    };
    console.log(
      `  ${def.id.padEnd(10)} ${round(result.width)}×${round(result.height)}  (${ids.length} nodes)`,
    );
  }

  const body = `/*
 * AUTO-GENERATED by scripts/precompute-stills-layout.mts — do not edit by hand.
 * Re-run \`pnpm stills:layout\` after changing STILL_DEFS.
 *
 * Baked ELK coordinates (+ bbox) for each promo still scenario, keyed by id, so
 * the stills render with zero async layout and are layout-identical to the manual.
 */

export interface StillLayoutResult {
  positions: Record<string, { x: number; y: number }>;
  width: number;
  height: number;
}

export const STILLS_LAYOUT: Record<string, StillLayoutResult> = ${JSON.stringify(
    out,
    null,
    2,
  )};
`;

  await writeFile(OUT, body, "utf8");
  console.log(`✓ wrote ${path.relative(process.cwd(), OUT)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
