#!/usr/bin/env node
/**
 * 构建前从 GitHub Releases 拉取 Latest 正式版，生成 download.generated.ts。
 * 公开 API、无需 token；失败时回退到 FALLBACK_VERSION（离线 dev 可用）。
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const RELEASES_REPO = "Lawofall/AgentCore-releases";
const FALLBACK_VERSION = "0.3.0";

const __dir = dirname(fileURLToPath(import.meta.url));

function fallbackArtifacts(version) {
  const base = `https://github.com/${RELEASES_REPO}/releases/download/v${version}`;
  return {
    version,
    releaseNotesUrl: `https://github.com/${RELEASES_REPO}/releases/tag/v${version}`,
    winUrl: `${base}/AgentCore-${version}-win-x64.exe`,
    winFilename: `AgentCore-${version}-win-x64.exe`,
    macUrl: `${base}/AgentCore-${version}-mac-arm64.dmg`,
    macFilename: `AgentCore-${version}-mac-arm64.dmg`,
  };
}

async function fetchLatest() {
  const res = await fetch(
    `https://api.github.com/repos/${RELEASES_REPO}/releases/latest`,
    { headers: { "User-Agent": "agentcore-website-build" } },
  );
  if (!res.ok) {
    throw new Error(`GitHub API ${res.status}`);
  }
  const data = await res.json();
  if (data.draft) {
    throw new Error(`Latest release ${data.tag_name} is still draft`);
  }
  const version = String(data.tag_name).replace(/^v/, "");
  const assets = data.assets ?? [];
  const winAsset = assets.find((a) => /-win-x64\.exe$/i.test(a.name));
  const macAsset = assets.find((a) => /-mac-arm64\.dmg$/i.test(a.name));
  const base = fallbackArtifacts(version);
  return {
    version,
    releaseNotesUrl: data.html_url,
    winUrl: winAsset?.browser_download_url ?? base.winUrl,
    winFilename: winAsset?.name ?? base.winFilename,
    macUrl: macAsset?.browser_download_url ?? "",
    macFilename: macAsset?.name ?? "",
  };
}

async function main() {
  let artifacts = fallbackArtifacts(FALLBACK_VERSION);
  try {
    artifacts = await fetchLatest();
    console.log(
      `fetch-release: latest v${artifacts.version}` +
        (artifacts.macUrl ? " (win+mac)" : " (win only)"),
    );
  } catch (err) {
    console.warn(
      `fetch-release: ${err instanceof Error ? err.message : err} — fallback v${FALLBACK_VERSION}`,
    );
  }

  const out = `/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-release.mjs — do not edit.
export const DESKTOP_VERSION = ${JSON.stringify(artifacts.version)};
export const RELEASE_NOTES_URL = ${JSON.stringify(artifacts.releaseNotesUrl)};
export const WIN_INSTALLER_URL = ${JSON.stringify(artifacts.winUrl)};
export const WIN_INSTALLER_FILENAME = ${JSON.stringify(artifacts.winFilename)};
export const MAC_DMG_URL = ${JSON.stringify(artifacts.macUrl)};
export const MAC_DMG_FILENAME = ${JSON.stringify(artifacts.macFilename)};
`;

  writeFileSync(join(__dir, "../src/lib/download.generated.ts"), out, "utf8");
}

main();
