"""Generate ``packages/contract-types/src/events.generated.ts`` from the payload registry.

Single source: :mod:`agentcore.runtime.events.payloads` (pydantic wire models +
``TS_EXPORTS`` emission plan). Event names stay in ``eventTypes.generated.ts``
(``dump_sse_event_types.py``); this script renders the payload SHAPES + ``SSEPayloadMap``.

Run as part of ``pnpm gen:types`` (or standalone)::

    uv run python scripts/dump_sse_payload_types.py

Field-convention mapping (see ``payloads/_base.py``): required -> ``x: T``; required
nullable -> ``x: T | null``; default -> ``x?: T``; plain ``= None`` -> ``x?: T | null``;
``absent()`` marker -> ``x?: T`` (never null on the wire).
"""

from __future__ import annotations

import inspect
import json
import types
from enum import StrEnum
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from agentcore.runtime.events.payloads import (
    EVENT_PAYLOAD_MODELS,
    TS_EXPORTS,
    TsAlias,
    TsInlineUnion,
    TsInterface,
    TsRaw,
)
from agentcore.runtime.events.types import EventType

HEADER = """\
// AUTO-GENERATED by apps/server/scripts/dump_sse_payload_types.py — do not edit.
// Single source: agentcore.runtime.events.payloads (pydantic wire models; factories in
// runtime/events/*.py remain the only construction path).
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_sse_payload_types.py)

import type { SSEEventType } from "./eventTypes.generated";

export type { SSEEventType } from "./eventTypes.generated";

export interface SSEEvent<T = unknown> {
  type: SSEEventType;
  timestamp: string;
  payload: T;
}
"""

_NONE = type(None)


class _Names:
    """TS name lookup for models and registered aliases."""

    def __init__(self) -> None:
        self.models: dict[type[BaseModel], str] = {}
        self.aliases: list[tuple[Any, str]] = []

    def for_model(self, model: type[BaseModel]) -> str:
        try:
            return self.models[model]
        except KeyError:
            raise RuntimeError(
                f"model {model.__module__}.{model.__qualname__} referenced by a field but "
                "not registered in TS_EXPORTS"
            ) from None

    def for_alias(self, obj: Any) -> str | None:
        for known, name in self.aliases:
            if known is obj or known == obj:
                return name
        return None


def _literal_union(args: tuple[Any, ...]) -> str:
    return " | ".join(json.dumps(a) for a in args)


def _ts_type(ann: Any, names: _Names) -> str:
    """Map a Python annotation to TS source text (None already stripped by caller
    for the field-level null; nested Nones render as ``null``)."""
    if ann is _NONE:
        return "null"
    alias = names.for_alias(ann)
    if alias:
        return alias
    if ann is str:
        return "string"
    if ann in (int, float):
        return "number"
    if ann is bool:
        return "boolean"
    if ann is Any:
        return "unknown"
    if ann is dict:
        return "Record<string, unknown>"
    if ann is list:
        return "unknown[]"
    if isinstance(ann, type) and issubclass(ann, StrEnum):
        return _literal_union(tuple(e.value for e in ann))
    if isinstance(ann, type) and issubclass(ann, BaseModel):
        return names.for_model(ann)

    origin = get_origin(ann)
    args = get_args(ann)
    if origin is Literal:
        return _literal_union(args)
    if origin in (list, set, frozenset):
        inner = _ts_type(args[0], names)
        if " | " in inner:
            inner = f"({inner})"
        return f"{inner}[]"
    if origin is dict:
        key = _ts_type(args[0], names) if args else "string"
        val = _ts_type(args[1], names) if args else "unknown"
        return f"Record<{key}, {val}>"
    if origin is tuple:
        return "[" + ", ".join(_ts_type(a, names) for a in args) + "]"
    if origin in (Union, types.UnionType):
        return " | ".join(_ts_type(a, names) for a in args)
    raise RuntimeError(f"unsupported annotation for TS emission: {ann!r}")


def _split_none(ann: Any) -> tuple[Any, bool]:
    """Strip NoneType off a top-level union; returns (rest, had_none)."""
    if get_origin(ann) in (Union, types.UnionType):
        args = tuple(a for a in get_args(ann) if a is not _NONE)
        had_none = len(args) != len(get_args(ann))
        if len(args) == 1:
            return args[0], had_none
        return Union[args], had_none  # noqa: UP007 — reconstructing typing union
    return ann, False


def _jsdoc(text: str, indent: str = "") -> list[str]:
    lines = [ln.rstrip() for ln in inspect.cleandoc(text).splitlines()]
    if not lines:
        return []
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    out = [f"{indent}/** {lines[0]}"]
    out.extend(f"{indent} * {ln}" for ln in lines[1:])
    out[-1] += " */"
    return out


def _field_lines(
    name: str, fi: FieldInfo, names: _Names, force_required: frozenset[str]
) -> list[str]:
    extra = fi.json_schema_extra if isinstance(fi.json_schema_extra, dict) else {}
    ts_override = extra.get("ts_type")
    absent_mark = extra.get("ts") == "absent"
    required = fi.is_required() or name in force_required
    rest, had_none = _split_none(fi.annotation)
    ts = str(ts_override) if ts_override else _ts_type(rest, names)
    wire_name = fi.alias or name

    if required:
        rendered = f"{wire_name}: {ts}" + (" | null" if had_none else "")
    elif absent_mark or not had_none:
        rendered = f"{wire_name}?: {ts}"
    else:
        rendered = f"{wire_name}?: {ts} | null"

    lines: list[str] = []
    if fi.description:
        lines.extend(_jsdoc(fi.description, indent="  "))
    lines.append(f"  {rendered};")
    return lines


def _own_fields(model: type[BaseModel], base: type[BaseModel] | None) -> list[str]:
    if base is None:
        return list(model.model_fields)
    return [n for n in model.model_fields if n not in base.model_fields]


def _emit_interface(spec: TsInterface, names: _Names) -> list[str]:
    doc = spec.doc or (spec.model.__doc__ or "")
    out: list[str] = []
    if doc.strip():
        out.extend(_jsdoc(doc))
    if spec.render_raw:
        out.append(f"export type {spec.ts_name} = {spec.render_raw};")
        return out
    head = f"export interface {spec.ts_name}"
    if spec.extends is not None:
        head += f" extends {names.for_model(spec.extends)}"
    out.append(head + " {")
    for fname in _own_fields(spec.model, spec.extends):
        out.extend(
            _field_lines(fname, spec.model.model_fields[fname], names, spec.force_required)
        )
    out.append("}")
    return out


def _emit_alias(spec: TsAlias, names: _Names) -> list[str]:
    if isinstance(spec.obj, type) and issubclass(spec.obj, StrEnum):
        values = tuple(e.value for e in spec.obj)
    elif get_origin(spec.obj) is Literal:
        values = get_args(spec.obj)
    else:
        raise RuntimeError(f"TsAlias {spec.name}: unsupported source {spec.obj!r}")
    out: list[str] = []
    if spec.doc.strip():
        out.extend(_jsdoc(spec.doc))
    if len(values) <= 3:
        out.append(f"export type {spec.name} = {_literal_union(values)};")
    else:
        out.append(f"export type {spec.name} =")
        for i, v in enumerate(values):
            tail = ";" if i == len(values) - 1 else ""
            out.append(f"  | {json.dumps(v)}{tail}")
    return out


def _emit_inline_union(spec: TsInlineUnion, names: _Names) -> list[str]:
    out: list[str] = []
    if spec.doc.strip():
        out.extend(_jsdoc(spec.doc))
    out.append(f"export type {spec.name} =")
    for i, member in enumerate(spec.members):
        parts: list[str] = []
        for fname, fi in member.model_fields.items():
            lines = _field_lines(fname, fi, names, frozenset())
            # inline members carry no per-field JSDoc; take the declaration line only
            parts.append(lines[-1].strip().rstrip(";"))
        tail = ";" if i == len(spec.members) - 1 else ""
        out.append(f"  | {{ {'; '.join(parts)} }}{tail}")
    return out


def _emit_payload_map(names: _Names) -> list[str]:
    out = ["export type SSEPayloadMap = {"]
    for event, model in EVENT_PAYLOAD_MODELS.items():
        key = event.value if "." not in event.value else json.dumps(event.value)
        out.append(f"  {key}: {names.for_model(model)};")
    out.append("};")
    return out


def build() -> str:
    names = _Names()
    for spec in TS_EXPORTS:
        if isinstance(spec, TsInterface):
            names.models[spec.model] = spec.ts_name
        elif isinstance(spec, TsAlias):
            names.aliases.append((spec.obj, spec.name))

    missing = set(EventType) - set(EVENT_PAYLOAD_MODELS)
    extra = set(EVENT_PAYLOAD_MODELS) - set(EventType)
    if missing or extra:
        raise RuntimeError(
            f"EVENT_PAYLOAD_MODELS drift — missing: {sorted(e.value for e in missing)}, "
            f"extra: {sorted(e.value for e in extra)}"
        )
    for event, model in EVENT_PAYLOAD_MODELS.items():
        if model not in names.models:
            raise RuntimeError(f"{event.value}: payload model not registered in TS_EXPORTS")

    chunks: list[str] = [HEADER.rstrip()]
    for spec in TS_EXPORTS:
        if isinstance(spec, TsInterface):
            chunks.append("\n".join(_emit_interface(spec, names)))
        elif isinstance(spec, TsAlias):
            chunks.append("\n".join(_emit_alias(spec, names)))
        elif isinstance(spec, TsInlineUnion):
            chunks.append("\n".join(_emit_inline_union(spec, names)))
        elif isinstance(spec, TsRaw):
            block = _jsdoc(spec.doc) if spec.doc.strip() else []
            block.append(f"export type {spec.name} = {spec.ts};")
            chunks.append("\n".join(block))
    chunks.append("\n".join(_emit_payload_map(names)))
    return "\n\n".join(chunks) + "\n"


def main() -> None:
    content = build()
    out = (
        Path(__file__).resolve().parents[3]
        / "packages"
        / "contract-types"
        / "src"
        / "events.generated.ts"
    )
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out} ({len(EVENT_PAYLOAD_MODELS)} event payloads)")


if __name__ == "__main__":
    main()
