"""Generate ``packages/contract-types/src/eventTypes.generated.ts`` from EventType.

The Python ``EventType`` enum is the wire-contract single source for SSE event
names. Payload shapes are generated from ``runtime/events/payloads/`` wire models
via ``scripts/dump_sse_payload_types.py``.

Run as part of ``pnpm gen:types`` (or standalone after changing EventType)::

    uv run python scripts/dump_sse_event_types.py
"""

from __future__ import annotations

from pathlib import Path

from agentcore.runtime.events.types import EventType

HEADER = """\
// AUTO-GENERATED by apps/server/scripts/dump_sse_event_types.py — do not edit.
// Single source: agentcore.runtime.events.types.EventType
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_sse_event_types.py)
"""


def main() -> None:
    values = sorted(e.value for e in EventType)
    lines = [HEADER.rstrip(), "export type SSEEventType ="]
    for v in values:
        lines.append(f'  | "{v}"')
    lines[-1] = f"{lines[-1]};"
    content = "\n".join(lines) + "\n"

    out = (
        Path(__file__).resolve().parents[3]
        / "packages"
        / "contract-types"
        / "src"
        / "eventTypes.generated.ts"
    )
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out} ({len(values)} event types)")


if __name__ == "__main__":
    main()
