"""Generate ``packages/contract-types/src/errorCodes.generated.ts``.

Single source: ``agentcore.core.error_codes.ErrorCode``.

Run as part of ``pnpm gen:types`` (or standalone)::

    uv run python scripts/dump_error_codes.py
"""

from __future__ import annotations

from pathlib import Path

from agentcore.core.error_codes import ErrorCode

HEADER = """\
// AUTO-GENERATED by apps/server/scripts/dump_error_codes.py — do not edit.
// Single source: agentcore.core.error_codes.ErrorCode
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_error_codes.py)
"""


def main() -> None:
    # Preserve declaration order from the StrEnum (grouped by origin in the source).
    values = [e.value for e in ErrorCode]

    lines = [HEADER.rstrip(), ""]
    lines.append(
        "/** The canonical code list — runtime catalog derived from backend ErrorCode. */"
    )
    lines.append("export const ERROR_CODES = [")
    for v in values:
        lines.append(f'  "{v}",')
    lines.append("] as const;")
    lines.append("")
    lines.append(
        "/** A backend error code: SSE `error` event or REST `{error:{code}}`. */"
    )
    lines.append("export type ErrorCode = (typeof ERROR_CODES)[number];")
    lines.append("")

    content = "\n".join(lines)
    out = (
        Path(__file__).resolve().parents[3]
        / "packages"
        / "contract-types"
        / "src"
        / "errorCodes.generated.ts"
    )
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out} ({len(values)} error codes)")


if __name__ == "__main__":
    main()
