"""Generate ``packages/contract-rest-types/src/paths.generated.ts``.

Single source: ``apps/server/openapi.json`` ``paths`` keys.

Run as part of ``pnpm gen:types`` (or standalone)::

    uv run python scripts/dump_rest_paths.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OPENAPI = ROOT / "apps" / "server" / "openapi.json"
OUT = ROOT / "packages" / "contract-rest-types" / "src" / "paths.generated.ts"

HEADER = """\
// AUTO-GENERATED by apps/server/scripts/dump_rest_paths.py — do not edit.
// Single source: apps/server/openapi.json paths
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_rest_paths.py)
"""


def main() -> None:
    data = json.loads(OPENAPI.read_text(encoding="utf-8"))
    paths = data.get("paths")
    if not isinstance(paths, dict) or not paths:
        raise SystemExit("openapi.json has no paths object")

    templates = sorted(str(p) for p in paths.keys())

    lines = [HEADER.rstrip(), ""]
    lines.append(
        "/** OpenAPI path templates (path-param braces preserved). */"
    )
    lines.append("export const REST_PATH_TEMPLATES = [")
    for t in templates:
        lines.append(f'  "{t}",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export type RestPathTemplate = (typeof REST_PATH_TEMPLATES)[number];")
    lines.append("")
    lines.append(
        "/** Fill `{param}` segments. Missing keys throw; values are URI-encoded. */"
    )
    lines.append(
        "export function restPath("
    )
    lines.append("  template: RestPathTemplate,")
    lines.append("  params: Record<string, string | number> = {},")
    lines.append("): string {")
    lines.append(
        "  return template.replace(/\\{([a-zA-Z_][a-zA-Z0-9_]*)\\}/g, (_m, name: string) => {"
    )
    lines.append("    if (!(name in params)) {")
    lines.append(
        "      throw new Error(`restPath: missing param \"${name}\" for ${template}`);"
    )
    lines.append("    }")
    lines.append("    return encodeURIComponent(String(params[name]));")
    lines.append("  });")
    lines.append("}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(templates)} path templates)")


if __name__ == "__main__":
    main()
